// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth.proto

//

package auth_service

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_struct "github.com/golang/protobuf/ptypes/struct"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LoginStrategies int32

const (
	LoginStrategies_UNKNOWN  LoginStrategies = 0
	LoginStrategies_STANDARD LoginStrategies = 1
	LoginStrategies_OTP      LoginStrategies = 2
	LoginStrategies_PASSCODE LoginStrategies = 3
	LoginStrategies_ONE2MANY LoginStrategies = 4
)

var LoginStrategies_name = map[int32]string{
	0: "UNKNOWN",
	1: "STANDARD",
	2: "OTP",
	3: "PASSCODE",
	4: "ONE2MANY",
}

var LoginStrategies_value = map[string]int32{
	"UNKNOWN":  0,
	"STANDARD": 1,
	"OTP":      2,
	"PASSCODE": 3,
	"ONE2MANY": 4,
}

func (x LoginStrategies) String() string {
	return proto.EnumName(LoginStrategies_name, int32(x))
}

func (LoginStrategies) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{0}
}

type ConfirmStrategies int32

const (
	ConfirmStrategies_UNDECIDED ConfirmStrategies = 0
	ConfirmStrategies_PHONE     ConfirmStrategies = 1
	ConfirmStrategies_EMAIL     ConfirmStrategies = 2
)

var ConfirmStrategies_name = map[int32]string{
	0: "UNDECIDED",
	1: "PHONE",
	2: "EMAIL",
}

var ConfirmStrategies_value = map[string]int32{
	"UNDECIDED": 0,
	"PHONE":     1,
	"EMAIL":     2,
}

func (x ConfirmStrategies) String() string {
	return proto.EnumName(ConfirmStrategies_name, int32(x))
}

func (ConfirmStrategies) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{1}
}

type RelationTypes int32

const (
	RelationTypes_UNREVEALED RelationTypes = 0
	RelationTypes_BRANCH     RelationTypes = 1
	RelationTypes_REGION     RelationTypes = 2
)

var RelationTypes_name = map[int32]string{
	0: "UNREVEALED",
	1: "BRANCH",
	2: "REGION",
}

var RelationTypes_value = map[string]int32{
	"UNREVEALED": 0,
	"BRANCH":     1,
	"REGION":     2,
}

func (x RelationTypes) String() string {
	return proto.EnumName(RelationTypes_name, int32(x))
}

func (RelationTypes) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{2}
}

type ClientPlatform struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProjectId            string   `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Subdomain            string   `protobuf:"bytes,4,opt,name=subdomain,proto3" json:"subdomain,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientPlatform) Reset()         { *m = ClientPlatform{} }
func (m *ClientPlatform) String() string { return proto.CompactTextString(m) }
func (*ClientPlatform) ProtoMessage()    {}
func (*ClientPlatform) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{0}
}

func (m *ClientPlatform) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientPlatform.Unmarshal(m, b)
}
func (m *ClientPlatform) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientPlatform.Marshal(b, m, deterministic)
}
func (m *ClientPlatform) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientPlatform.Merge(m, src)
}
func (m *ClientPlatform) XXX_Size() int {
	return xxx_messageInfo_ClientPlatform.Size(m)
}
func (m *ClientPlatform) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientPlatform.DiscardUnknown(m)
}

var xxx_messageInfo_ClientPlatform proto.InternalMessageInfo

func (m *ClientPlatform) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ClientPlatform) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

func (m *ClientPlatform) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ClientPlatform) GetSubdomain() string {
	if m != nil {
		return m.Subdomain
	}
	return ""
}

type ClientType struct {
	Id                   string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string            `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ConfirmBy            ConfirmStrategies `protobuf:"varint,3,opt,name=confirm_by,json=confirmBy,proto3,enum=auth_service.ConfirmStrategies" json:"confirm_by,omitempty"`
	SelfRegister         bool              `protobuf:"varint,4,opt,name=self_register,json=selfRegister,proto3" json:"self_register,omitempty"`
	SelfRecover          bool              `protobuf:"varint,5,opt,name=self_recover,json=selfRecover,proto3" json:"self_recover,omitempty"`
	ProjectId            string            `protobuf:"bytes,6,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ClientType) Reset()         { *m = ClientType{} }
func (m *ClientType) String() string { return proto.CompactTextString(m) }
func (*ClientType) ProtoMessage()    {}
func (*ClientType) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{1}
}

func (m *ClientType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientType.Unmarshal(m, b)
}
func (m *ClientType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientType.Marshal(b, m, deterministic)
}
func (m *ClientType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientType.Merge(m, src)
}
func (m *ClientType) XXX_Size() int {
	return xxx_messageInfo_ClientType.Size(m)
}
func (m *ClientType) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientType.DiscardUnknown(m)
}

var xxx_messageInfo_ClientType proto.InternalMessageInfo

func (m *ClientType) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ClientType) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ClientType) GetConfirmBy() ConfirmStrategies {
	if m != nil {
		return m.ConfirmBy
	}
	return ConfirmStrategies_UNDECIDED
}

func (m *ClientType) GetSelfRegister() bool {
	if m != nil {
		return m.SelfRegister
	}
	return false
}

func (m *ClientType) GetSelfRecover() bool {
	if m != nil {
		return m.SelfRecover
	}
	return false
}

func (m *ClientType) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

type Relation struct {
	Id                   string        `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ClientTypeId         string        `protobuf:"bytes,2,opt,name=client_type_id,json=clientTypeId,proto3" json:"client_type_id,omitempty"`
	Type                 RelationTypes `protobuf:"varint,3,opt,name=type,proto3,enum=auth_service.RelationTypes" json:"type,omitempty"`
	Name                 string        `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Description          string        `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Relation) Reset()         { *m = Relation{} }
func (m *Relation) String() string { return proto.CompactTextString(m) }
func (*Relation) ProtoMessage()    {}
func (*Relation) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{2}
}

func (m *Relation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Relation.Unmarshal(m, b)
}
func (m *Relation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Relation.Marshal(b, m, deterministic)
}
func (m *Relation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Relation.Merge(m, src)
}
func (m *Relation) XXX_Size() int {
	return xxx_messageInfo_Relation.Size(m)
}
func (m *Relation) XXX_DiscardUnknown() {
	xxx_messageInfo_Relation.DiscardUnknown(m)
}

var xxx_messageInfo_Relation proto.InternalMessageInfo

func (m *Relation) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Relation) GetClientTypeId() string {
	if m != nil {
		return m.ClientTypeId
	}
	return ""
}

func (m *Relation) GetType() RelationTypes {
	if m != nil {
		return m.Type
	}
	return RelationTypes_UNREVEALED
}

func (m *Relation) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Relation) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type UserInfoField struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ClientTypeId         string   `protobuf:"bytes,2,opt,name=client_type_id,json=clientTypeId,proto3" json:"client_type_id,omitempty"`
	FieldName            string   `protobuf:"bytes,3,opt,name=field_name,json=fieldName,proto3" json:"field_name,omitempty"`
	FieldType            string   `protobuf:"bytes,4,opt,name=field_type,json=fieldType,proto3" json:"field_type,omitempty"`
	DataType             string   `protobuf:"bytes,5,opt,name=data_type,json=dataType,proto3" json:"data_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfoField) Reset()         { *m = UserInfoField{} }
func (m *UserInfoField) String() string { return proto.CompactTextString(m) }
func (*UserInfoField) ProtoMessage()    {}
func (*UserInfoField) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{3}
}

func (m *UserInfoField) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfoField.Unmarshal(m, b)
}
func (m *UserInfoField) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfoField.Marshal(b, m, deterministic)
}
func (m *UserInfoField) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfoField.Merge(m, src)
}
func (m *UserInfoField) XXX_Size() int {
	return xxx_messageInfo_UserInfoField.Size(m)
}
func (m *UserInfoField) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfoField.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfoField proto.InternalMessageInfo

func (m *UserInfoField) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UserInfoField) GetClientTypeId() string {
	if m != nil {
		return m.ClientTypeId
	}
	return ""
}

func (m *UserInfoField) GetFieldName() string {
	if m != nil {
		return m.FieldName
	}
	return ""
}

func (m *UserInfoField) GetFieldType() string {
	if m != nil {
		return m.FieldType
	}
	return ""
}

func (m *UserInfoField) GetDataType() string {
	if m != nil {
		return m.DataType
	}
	return ""
}

type Client struct {
	ClientPlatformId     string          `protobuf:"bytes,1,opt,name=client_platform_id,json=clientPlatformId,proto3" json:"client_platform_id,omitempty"`
	ClientTypeId         string          `protobuf:"bytes,2,opt,name=client_type_id,json=clientTypeId,proto3" json:"client_type_id,omitempty"`
	LoginStrategy        LoginStrategies `protobuf:"varint,3,opt,name=login_strategy,json=loginStrategy,proto3,enum=auth_service.LoginStrategies" json:"login_strategy,omitempty"`
	ProjectId            string          `protobuf:"bytes,4,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Client) Reset()         { *m = Client{} }
func (m *Client) String() string { return proto.CompactTextString(m) }
func (*Client) ProtoMessage()    {}
func (*Client) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{4}
}

func (m *Client) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Client.Unmarshal(m, b)
}
func (m *Client) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Client.Marshal(b, m, deterministic)
}
func (m *Client) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Client.Merge(m, src)
}
func (m *Client) XXX_Size() int {
	return xxx_messageInfo_Client.Size(m)
}
func (m *Client) XXX_DiscardUnknown() {
	xxx_messageInfo_Client.DiscardUnknown(m)
}

var xxx_messageInfo_Client proto.InternalMessageInfo

func (m *Client) GetClientPlatformId() string {
	if m != nil {
		return m.ClientPlatformId
	}
	return ""
}

func (m *Client) GetClientTypeId() string {
	if m != nil {
		return m.ClientTypeId
	}
	return ""
}

func (m *Client) GetLoginStrategy() LoginStrategies {
	if m != nil {
		return m.LoginStrategy
	}
	return LoginStrategies_UNKNOWN
}

func (m *Client) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

type Role struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ClientTypeId         string   `protobuf:"bytes,2,opt,name=client_type_id,json=clientTypeId,proto3" json:"client_type_id,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	ClientPlatformId     string   `protobuf:"bytes,4,opt,name=client_platform_id,json=clientPlatformId,proto3" json:"client_platform_id,omitempty"`
	ProjectId            string   `protobuf:"bytes,5,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Role) Reset()         { *m = Role{} }
func (m *Role) String() string { return proto.CompactTextString(m) }
func (*Role) ProtoMessage()    {}
func (*Role) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{5}
}

func (m *Role) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Role.Unmarshal(m, b)
}
func (m *Role) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Role.Marshal(b, m, deterministic)
}
func (m *Role) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Role.Merge(m, src)
}
func (m *Role) XXX_Size() int {
	return xxx_messageInfo_Role.Size(m)
}
func (m *Role) XXX_DiscardUnknown() {
	xxx_messageInfo_Role.DiscardUnknown(m)
}

var xxx_messageInfo_Role proto.InternalMessageInfo

func (m *Role) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Role) GetClientTypeId() string {
	if m != nil {
		return m.ClientTypeId
	}
	return ""
}

func (m *Role) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Role) GetClientPlatformId() string {
	if m != nil {
		return m.ClientPlatformId
	}
	return ""
}

func (m *Role) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

type Scope struct {
	ClientPlatformId     string   `protobuf:"bytes,1,opt,name=client_platform_id,json=clientPlatformId,proto3" json:"client_platform_id,omitempty"`
	Path                 string   `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Method               string   `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	Requests             int64    `protobuf:"varint,4,opt,name=requests,proto3" json:"requests,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Scope) Reset()         { *m = Scope{} }
func (m *Scope) String() string { return proto.CompactTextString(m) }
func (*Scope) ProtoMessage()    {}
func (*Scope) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{6}
}

func (m *Scope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Scope.Unmarshal(m, b)
}
func (m *Scope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Scope.Marshal(b, m, deterministic)
}
func (m *Scope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Scope.Merge(m, src)
}
func (m *Scope) XXX_Size() int {
	return xxx_messageInfo_Scope.Size(m)
}
func (m *Scope) XXX_DiscardUnknown() {
	xxx_messageInfo_Scope.DiscardUnknown(m)
}

var xxx_messageInfo_Scope proto.InternalMessageInfo

func (m *Scope) GetClientPlatformId() string {
	if m != nil {
		return m.ClientPlatformId
	}
	return ""
}

func (m *Scope) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Scope) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *Scope) GetRequests() int64 {
	if m != nil {
		return m.Requests
	}
	return 0
}

type Permission struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ClientPlatformId     string   `protobuf:"bytes,2,opt,name=client_platform_id,json=clientPlatformId,proto3" json:"client_platform_id,omitempty"`
	ParentId             string   `protobuf:"bytes,3,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Permission) Reset()         { *m = Permission{} }
func (m *Permission) String() string { return proto.CompactTextString(m) }
func (*Permission) ProtoMessage()    {}
func (*Permission) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{7}
}

func (m *Permission) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Permission.Unmarshal(m, b)
}
func (m *Permission) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Permission.Marshal(b, m, deterministic)
}
func (m *Permission) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Permission.Merge(m, src)
}
func (m *Permission) XXX_Size() int {
	return xxx_messageInfo_Permission.Size(m)
}
func (m *Permission) XXX_DiscardUnknown() {
	xxx_messageInfo_Permission.DiscardUnknown(m)
}

var xxx_messageInfo_Permission proto.InternalMessageInfo

func (m *Permission) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Permission) GetClientPlatformId() string {
	if m != nil {
		return m.ClientPlatformId
	}
	return ""
}

func (m *Permission) GetParentId() string {
	if m != nil {
		return m.ParentId
	}
	return ""
}

func (m *Permission) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type PermissionScope struct {
	PermissionId         string   `protobuf:"bytes,1,opt,name=permission_id,json=permissionId,proto3" json:"permission_id,omitempty"`
	ClientPlatformId     string   `protobuf:"bytes,2,opt,name=client_platform_id,json=clientPlatformId,proto3" json:"client_platform_id,omitempty"`
	Path                 string   `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Method               string   `protobuf:"bytes,4,opt,name=method,proto3" json:"method,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PermissionScope) Reset()         { *m = PermissionScope{} }
func (m *PermissionScope) String() string { return proto.CompactTextString(m) }
func (*PermissionScope) ProtoMessage()    {}
func (*PermissionScope) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{8}
}

func (m *PermissionScope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PermissionScope.Unmarshal(m, b)
}
func (m *PermissionScope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PermissionScope.Marshal(b, m, deterministic)
}
func (m *PermissionScope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PermissionScope.Merge(m, src)
}
func (m *PermissionScope) XXX_Size() int {
	return xxx_messageInfo_PermissionScope.Size(m)
}
func (m *PermissionScope) XXX_DiscardUnknown() {
	xxx_messageInfo_PermissionScope.DiscardUnknown(m)
}

var xxx_messageInfo_PermissionScope proto.InternalMessageInfo

func (m *PermissionScope) GetPermissionId() string {
	if m != nil {
		return m.PermissionId
	}
	return ""
}

func (m *PermissionScope) GetClientPlatformId() string {
	if m != nil {
		return m.ClientPlatformId
	}
	return ""
}

func (m *PermissionScope) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *PermissionScope) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

type RolePermission struct {
	RoleId               string   `protobuf:"bytes,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	PermissionId         string   `protobuf:"bytes,2,opt,name=permission_id,json=permissionId,proto3" json:"permission_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RolePermission) Reset()         { *m = RolePermission{} }
func (m *RolePermission) String() string { return proto.CompactTextString(m) }
func (*RolePermission) ProtoMessage()    {}
func (*RolePermission) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{9}
}

func (m *RolePermission) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RolePermission.Unmarshal(m, b)
}
func (m *RolePermission) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RolePermission.Marshal(b, m, deterministic)
}
func (m *RolePermission) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RolePermission.Merge(m, src)
}
func (m *RolePermission) XXX_Size() int {
	return xxx_messageInfo_RolePermission.Size(m)
}
func (m *RolePermission) XXX_DiscardUnknown() {
	xxx_messageInfo_RolePermission.DiscardUnknown(m)
}

var xxx_messageInfo_RolePermission proto.InternalMessageInfo

func (m *RolePermission) GetRoleId() string {
	if m != nil {
		return m.RoleId
	}
	return ""
}

func (m *RolePermission) GetPermissionId() string {
	if m != nil {
		return m.PermissionId
	}
	return ""
}

type User struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProjectId            string   `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	ClientPlatformId     string   `protobuf:"bytes,3,opt,name=client_platform_id,json=clientPlatformId,proto3" json:"client_platform_id,omitempty"`
	ClientTypeId         string   `protobuf:"bytes,4,opt,name=client_type_id,json=clientTypeId,proto3" json:"client_type_id,omitempty"`
	RoleId               string   `protobuf:"bytes,5,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	Phone                string   `protobuf:"bytes,6,opt,name=phone,proto3" json:"phone,omitempty"`
	Email                string   `protobuf:"bytes,7,opt,name=email,proto3" json:"email,omitempty"`
	Login                string   `protobuf:"bytes,8,opt,name=login,proto3" json:"login,omitempty"`
	Password             string   `protobuf:"bytes,9,opt,name=password,proto3" json:"password,omitempty"`
	Active               int32    `protobuf:"varint,10,opt,name=active,proto3" json:"active,omitempty"`
	ExpiresAt            string   `protobuf:"bytes,11,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	CreatedAt            string   `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Name                 string   `protobuf:"bytes,14,opt,name=name,proto3" json:"name,omitempty"`
	PhotoUrl             string   `protobuf:"bytes,15,opt,name=photo_url,json=photoUrl,proto3" json:"photo_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{10}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

func (m *User) GetClientPlatformId() string {
	if m != nil {
		return m.ClientPlatformId
	}
	return ""
}

func (m *User) GetClientTypeId() string {
	if m != nil {
		return m.ClientTypeId
	}
	return ""
}

func (m *User) GetRoleId() string {
	if m != nil {
		return m.RoleId
	}
	return ""
}

func (m *User) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetActive() int32 {
	if m != nil {
		return m.Active
	}
	return 0
}

func (m *User) GetExpiresAt() string {
	if m != nil {
		return m.ExpiresAt
	}
	return ""
}

func (m *User) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *User) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetPhotoUrl() string {
	if m != nil {
		return m.PhotoUrl
	}
	return ""
}

type UserRelation struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RelationId           string   `protobuf:"bytes,2,opt,name=relation_id,json=relationId,proto3" json:"relation_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRelation) Reset()         { *m = UserRelation{} }
func (m *UserRelation) String() string { return proto.CompactTextString(m) }
func (*UserRelation) ProtoMessage()    {}
func (*UserRelation) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{11}
}

func (m *UserRelation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRelation.Unmarshal(m, b)
}
func (m *UserRelation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRelation.Marshal(b, m, deterministic)
}
func (m *UserRelation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRelation.Merge(m, src)
}
func (m *UserRelation) XXX_Size() int {
	return xxx_messageInfo_UserRelation.Size(m)
}
func (m *UserRelation) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRelation.DiscardUnknown(m)
}

var xxx_messageInfo_UserRelation proto.InternalMessageInfo

func (m *UserRelation) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UserRelation) GetRelationId() string {
	if m != nil {
		return m.RelationId
	}
	return ""
}

type UserInfo struct {
	UserId               string          `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Data                 *_struct.Struct `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{12}
}

func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (m *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(m, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UserInfo) GetData() *_struct.Struct {
	if m != nil {
		return m.Data
	}
	return nil
}

type Session struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProjectId            string   `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	ClientPlatformId     string   `protobuf:"bytes,3,opt,name=client_platform_id,json=clientPlatformId,proto3" json:"client_platform_id,omitempty"`
	ClientTypeId         string   `protobuf:"bytes,4,opt,name=client_type_id,json=clientTypeId,proto3" json:"client_type_id,omitempty"`
	UserId               string   `protobuf:"bytes,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RoleId               string   `protobuf:"bytes,6,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	Ip                   string   `protobuf:"bytes,7,opt,name=ip,proto3" json:"ip,omitempty"`
	Data                 string   `protobuf:"bytes,8,opt,name=data,proto3" json:"data,omitempty"`
	ExpiresAt            string   `protobuf:"bytes,9,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	CreatedAt            string   `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	IntegrationId        string   `protobuf:"bytes,12,opt,name=integration_id,json=integrationId,proto3" json:"integration_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Session) Reset()         { *m = Session{} }
func (m *Session) String() string { return proto.CompactTextString(m) }
func (*Session) ProtoMessage()    {}
func (*Session) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{13}
}

func (m *Session) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Session.Unmarshal(m, b)
}
func (m *Session) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Session.Marshal(b, m, deterministic)
}
func (m *Session) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Session.Merge(m, src)
}
func (m *Session) XXX_Size() int {
	return xxx_messageInfo_Session.Size(m)
}
func (m *Session) XXX_DiscardUnknown() {
	xxx_messageInfo_Session.DiscardUnknown(m)
}

var xxx_messageInfo_Session proto.InternalMessageInfo

func (m *Session) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Session) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

func (m *Session) GetClientPlatformId() string {
	if m != nil {
		return m.ClientPlatformId
	}
	return ""
}

func (m *Session) GetClientTypeId() string {
	if m != nil {
		return m.ClientTypeId
	}
	return ""
}

func (m *Session) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Session) GetRoleId() string {
	if m != nil {
		return m.RoleId
	}
	return ""
}

func (m *Session) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *Session) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *Session) GetExpiresAt() string {
	if m != nil {
		return m.ExpiresAt
	}
	return ""
}

func (m *Session) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Session) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *Session) GetIntegrationId() string {
	if m != nil {
		return m.IntegrationId
	}
	return ""
}

type Passcode struct {
	Id                   string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProjectId            string            `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	ClientPlatformId     string            `protobuf:"bytes,3,opt,name=client_platform_id,json=clientPlatformId,proto3" json:"client_platform_id,omitempty"`
	ClientTypeId         string            `protobuf:"bytes,4,opt,name=client_type_id,json=clientTypeId,proto3" json:"client_type_id,omitempty"`
	UserId               string            `protobuf:"bytes,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ConfirmBy            ConfirmStrategies `protobuf:"varint,6,opt,name=confirm_by,json=confirmBy,proto3,enum=auth_service.ConfirmStrategies" json:"confirm_by,omitempty"`
	HashedCode           string            `protobuf:"bytes,7,opt,name=hashed_code,json=hashedCode,proto3" json:"hashed_code,omitempty"`
	State                int32             `protobuf:"varint,8,opt,name=state,proto3" json:"state,omitempty"`
	ExpiresAt            string            `protobuf:"bytes,9,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	CreatedAt            string            `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string            `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Passcode) Reset()         { *m = Passcode{} }
func (m *Passcode) String() string { return proto.CompactTextString(m) }
func (*Passcode) ProtoMessage()    {}
func (*Passcode) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{14}
}

func (m *Passcode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Passcode.Unmarshal(m, b)
}
func (m *Passcode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Passcode.Marshal(b, m, deterministic)
}
func (m *Passcode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Passcode.Merge(m, src)
}
func (m *Passcode) XXX_Size() int {
	return xxx_messageInfo_Passcode.Size(m)
}
func (m *Passcode) XXX_DiscardUnknown() {
	xxx_messageInfo_Passcode.DiscardUnknown(m)
}

var xxx_messageInfo_Passcode proto.InternalMessageInfo

func (m *Passcode) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Passcode) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

func (m *Passcode) GetClientPlatformId() string {
	if m != nil {
		return m.ClientPlatformId
	}
	return ""
}

func (m *Passcode) GetClientTypeId() string {
	if m != nil {
		return m.ClientTypeId
	}
	return ""
}

func (m *Passcode) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Passcode) GetConfirmBy() ConfirmStrategies {
	if m != nil {
		return m.ConfirmBy
	}
	return ConfirmStrategies_UNDECIDED
}

func (m *Passcode) GetHashedCode() string {
	if m != nil {
		return m.HashedCode
	}
	return ""
}

func (m *Passcode) GetState() int32 {
	if m != nil {
		return m.State
	}
	return 0
}

func (m *Passcode) GetExpiresAt() string {
	if m != nil {
		return m.ExpiresAt
	}
	return ""
}

func (m *Passcode) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Passcode) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

type Token struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken         string   `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	CreatedAt            string   `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	ExpiresAt            string   `protobuf:"bytes,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	RefreshInSeconds     int32    `protobuf:"varint,6,opt,name=refresh_in_seconds,json=refreshInSeconds,proto3" json:"refresh_in_seconds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Token) Reset()         { *m = Token{} }
func (m *Token) String() string { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()    {}
func (*Token) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{15}
}

func (m *Token) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Token.Unmarshal(m, b)
}
func (m *Token) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Token.Marshal(b, m, deterministic)
}
func (m *Token) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Token.Merge(m, src)
}
func (m *Token) XXX_Size() int {
	return xxx_messageInfo_Token.Size(m)
}
func (m *Token) XXX_DiscardUnknown() {
	xxx_messageInfo_Token.DiscardUnknown(m)
}

var xxx_messageInfo_Token proto.InternalMessageInfo

func (m *Token) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *Token) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

func (m *Token) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Token) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *Token) GetExpiresAt() string {
	if m != nil {
		return m.ExpiresAt
	}
	return ""
}

func (m *Token) GetRefreshInSeconds() int32 {
	if m != nil {
		return m.RefreshInSeconds
	}
	return 0
}

type Integration struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProjectId            string   `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	ClientPlatformId     string   `protobuf:"bytes,3,opt,name=client_platform_id,json=clientPlatformId,proto3" json:"client_platform_id,omitempty"`
	ClientTypeId         string   `protobuf:"bytes,4,opt,name=client_type_id,json=clientTypeId,proto3" json:"client_type_id,omitempty"`
	RoleId               string   `protobuf:"bytes,5,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	SecretKey            string   `protobuf:"bytes,6,opt,name=secret_key,json=secretKey,proto3" json:"secret_key,omitempty"`
	IpWhitelist          string   `protobuf:"bytes,7,opt,name=ip_whitelist,json=ipWhitelist,proto3" json:"ip_whitelist,omitempty"`
	Active               int32    `protobuf:"varint,8,opt,name=active,proto3" json:"active,omitempty"`
	ExpiresAt            string   `protobuf:"bytes,9,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	CreatedAt            string   `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Title                string   `protobuf:"bytes,12,opt,name=title,proto3" json:"title,omitempty"`
	Data                 string   `protobuf:"bytes,13,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Integration) Reset()         { *m = Integration{} }
func (m *Integration) String() string { return proto.CompactTextString(m) }
func (*Integration) ProtoMessage()    {}
func (*Integration) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{16}
}

func (m *Integration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Integration.Unmarshal(m, b)
}
func (m *Integration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Integration.Marshal(b, m, deterministic)
}
func (m *Integration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Integration.Merge(m, src)
}
func (m *Integration) XXX_Size() int {
	return xxx_messageInfo_Integration.Size(m)
}
func (m *Integration) XXX_DiscardUnknown() {
	xxx_messageInfo_Integration.DiscardUnknown(m)
}

var xxx_messageInfo_Integration proto.InternalMessageInfo

func (m *Integration) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Integration) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

func (m *Integration) GetClientPlatformId() string {
	if m != nil {
		return m.ClientPlatformId
	}
	return ""
}

func (m *Integration) GetClientTypeId() string {
	if m != nil {
		return m.ClientTypeId
	}
	return ""
}

func (m *Integration) GetRoleId() string {
	if m != nil {
		return m.RoleId
	}
	return ""
}

func (m *Integration) GetSecretKey() string {
	if m != nil {
		return m.SecretKey
	}
	return ""
}

func (m *Integration) GetIpWhitelist() string {
	if m != nil {
		return m.IpWhitelist
	}
	return ""
}

func (m *Integration) GetActive() int32 {
	if m != nil {
		return m.Active
	}
	return 0
}

func (m *Integration) GetExpiresAt() string {
	if m != nil {
		return m.ExpiresAt
	}
	return ""
}

func (m *Integration) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Integration) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *Integration) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Integration) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func init() {
	proto.RegisterEnum("auth_service.LoginStrategies", LoginStrategies_name, LoginStrategies_value)
	proto.RegisterEnum("auth_service.ConfirmStrategies", ConfirmStrategies_name, ConfirmStrategies_value)
	proto.RegisterEnum("auth_service.RelationTypes", RelationTypes_name, RelationTypes_value)
	proto.RegisterType((*ClientPlatform)(nil), "auth_service.ClientPlatform")
	proto.RegisterType((*ClientType)(nil), "auth_service.ClientType")
	proto.RegisterType((*Relation)(nil), "auth_service.Relation")
	proto.RegisterType((*UserInfoField)(nil), "auth_service.UserInfoField")
	proto.RegisterType((*Client)(nil), "auth_service.Client")
	proto.RegisterType((*Role)(nil), "auth_service.Role")
	proto.RegisterType((*Scope)(nil), "auth_service.Scope")
	proto.RegisterType((*Permission)(nil), "auth_service.Permission")
	proto.RegisterType((*PermissionScope)(nil), "auth_service.PermissionScope")
	proto.RegisterType((*RolePermission)(nil), "auth_service.RolePermission")
	proto.RegisterType((*User)(nil), "auth_service.User")
	proto.RegisterType((*UserRelation)(nil), "auth_service.UserRelation")
	proto.RegisterType((*UserInfo)(nil), "auth_service.UserInfo")
	proto.RegisterType((*Session)(nil), "auth_service.Session")
	proto.RegisterType((*Passcode)(nil), "auth_service.Passcode")
	proto.RegisterType((*Token)(nil), "auth_service.Token")
	proto.RegisterType((*Integration)(nil), "auth_service.Integration")
}

func init() { proto.RegisterFile("auth.proto", fileDescriptor_8bbd6f3875b0e874) }

var fileDescriptor_8bbd6f3875b0e874 = []byte{
	// 1228 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x57, 0xdd, 0x8e, 0xdb, 0x44,
	0x14, 0x6e, 0x12, 0x3b, 0x9b, 0x9c, 0xfc, 0x34, 0x58, 0x85, 0x8d, 0xda, 0xae, 0x5a, 0x5c, 0x90,
	0xaa, 0x52, 0xed, 0x4a, 0xe5, 0x02, 0xae, 0x90, 0xd2, 0x4d, 0xa0, 0x56, 0x5b, 0x6f, 0x70, 0x76,
	0xa9, 0xe0, 0xc6, 0xf2, 0xda, 0x27, 0xc9, 0x50, 0xc7, 0x76, 0x67, 0x26, 0x2d, 0x11, 0xe2, 0x05,
	0xb8, 0xe2, 0x05, 0x90, 0xb8, 0x82, 0xe7, 0xe0, 0x29, 0x90, 0x78, 0x00, 0x1e, 0x82, 0x2b, 0x34,
	0x3f, 0x4e, 0x9c, 0x6c, 0x76, 0xd5, 0xad, 0x40, 0xf4, 0x6e, 0xe6, 0x3b, 0xc7, 0xf6, 0x77, 0xbe,
	0xf3, 0x9d, 0xc9, 0x04, 0x20, 0x98, 0xf3, 0xe9, 0x7e, 0x46, 0x53, 0x9e, 0x5a, 0x4d, 0xb1, 0xf6,
	0x19, 0xd2, 0x97, 0x24, 0xc4, 0xeb, 0x37, 0x27, 0x69, 0x3a, 0x89, 0xf1, 0x40, 0xc6, 0x4e, 0xe7,
	0xe3, 0x03, 0xc6, 0xe9, 0x3c, 0xe4, 0x2a, 0xd7, 0x7e, 0x01, 0xed, 0xc3, 0x98, 0x60, 0xc2, 0x87,
	0x71, 0xc0, 0xc7, 0x29, 0x9d, 0x59, 0x6d, 0x28, 0x93, 0xa8, 0x5b, 0xba, 0x5d, 0xba, 0x5b, 0xf7,
	0xca, 0x24, 0xb2, 0xf6, 0x00, 0x32, 0x9a, 0x7e, 0x8b, 0x21, 0xf7, 0x49, 0xd4, 0x2d, 0x4b, 0xbc,
	0xae, 0x11, 0x27, 0xb2, 0x2c, 0x30, 0x92, 0x60, 0x86, 0xdd, 0x8a, 0x0c, 0xc8, 0xb5, 0x75, 0x13,
	0xea, 0x6c, 0x7e, 0x1a, 0xa5, 0xb3, 0x80, 0x24, 0x5d, 0x43, 0x3d, 0xb1, 0x04, 0xec, 0x3f, 0x4a,
	0x00, 0xea, 0x9b, 0xc7, 0x8b, 0x0c, 0xcf, 0x7c, 0x2f, 0x7f, 0x61, 0xb9, 0xf0, 0xc2, 0xcf, 0x00,
	0xc2, 0x34, 0x19, 0x13, 0x3a, 0xf3, 0x4f, 0x17, 0xf2, 0x53, 0xed, 0x07, 0xb7, 0xf6, 0x8b, 0x65,
	0xee, 0x1f, 0xaa, 0xf8, 0x88, 0xd3, 0x80, 0xe3, 0x84, 0x20, 0xf3, 0xea, 0xfa, 0x91, 0x87, 0x0b,
	0xeb, 0x0e, 0xb4, 0x18, 0xc6, 0x63, 0x9f, 0xe2, 0x84, 0x30, 0x8e, 0x54, 0x92, 0xaa, 0x79, 0x4d,
	0x01, 0x7a, 0x1a, 0xb3, 0xde, 0x87, 0xa6, 0x4e, 0x0a, 0xd3, 0x97, 0x48, 0xbb, 0xa6, 0xcc, 0x69,
	0xa8, 0x1c, 0x09, 0x6d, 0x68, 0x51, 0xdd, 0xd0, 0xc2, 0xfe, 0xad, 0x04, 0x35, 0x0f, 0xe3, 0x80,
	0x93, 0x34, 0x39, 0x53, 0xd7, 0x07, 0xd0, 0x0e, 0x65, 0xd5, 0x3e, 0x5f, 0x64, 0xb8, 0xd2, 0xb2,
	0x19, 0x2e, 0xb5, 0x70, 0x22, 0xeb, 0x00, 0x0c, 0x11, 0xd6, 0x35, 0xde, 0x58, 0xaf, 0x31, 0x7f,
	0xb7, 0xc8, 0x65, 0x9e, 0x4c, 0x5c, 0xca, 0x65, 0x14, 0xe4, 0xba, 0x0d, 0x8d, 0x08, 0x59, 0x48,
	0x49, 0x26, 0xb2, 0x65, 0x21, 0x75, 0xaf, 0x08, 0xd9, 0xbf, 0x94, 0xa0, 0x75, 0xc2, 0x90, 0x3a,
	0xc9, 0x38, 0xfd, 0x9c, 0x60, 0x1c, 0xbd, 0x21, 0xdd, 0x3d, 0x80, 0xb1, 0x78, 0xdc, 0x2f, 0x78,
	0xa0, 0x2e, 0x11, 0x57, 0x10, 0x59, 0x86, 0x65, 0x4d, 0x46, 0x21, 0x2c, 0x5b, 0x7f, 0x03, 0xea,
	0x51, 0xc0, 0x03, 0x15, 0x55, 0x2c, 0x6b, 0x02, 0x10, 0x41, 0xfb, 0xf7, 0x12, 0x54, 0x95, 0x4d,
	0xac, 0xfb, 0x60, 0x69, 0x2e, 0x99, 0x76, 0xa9, 0xbf, 0xe4, 0xda, 0x09, 0xd7, 0xec, 0xeb, 0xbc,
	0x2e, 0xf3, 0x3e, 0xb4, 0xe3, 0x74, 0x42, 0x12, 0x9f, 0x29, 0xc7, 0xe4, 0xb6, 0xda, 0x5b, 0x97,
	0xfc, 0x89, 0xc8, 0x29, 0x98, 0xaa, 0x15, 0x17, 0x80, 0xc5, 0x86, 0x21, 0x8c, 0x4d, 0x43, 0xfc,
	0x5c, 0x02, 0xc3, 0x4b, 0x63, 0x7c, 0x43, 0x75, 0xb7, 0xcd, 0xd6, 0x76, 0x2d, 0x8c, 0x73, 0xb4,
	0x58, 0xe7, 0x67, 0x6e, 0xf2, 0xfb, 0x01, 0xcc, 0x51, 0x98, 0x66, 0x78, 0x49, 0x85, 0x2d, 0x30,
	0xb2, 0x80, 0x4f, 0xf3, 0x11, 0x15, 0x6b, 0xeb, 0x3d, 0xa8, 0xce, 0x90, 0x4f, 0xd3, 0x48, 0xb3,
	0xd5, 0x3b, 0xeb, 0x3a, 0xd4, 0x28, 0xbe, 0x98, 0x23, 0xe3, 0x4c, 0xb2, 0xac, 0x78, 0xcb, 0xbd,
	0xfd, 0x3d, 0xc0, 0x10, 0xe9, 0x8c, 0x30, 0xb6, 0x6d, 0x60, 0xb6, 0x73, 0x2a, 0x9f, 0xc3, 0xe9,
	0x06, 0xd4, 0xb3, 0x80, 0x8a, 0x6c, 0x92, 0x53, 0xa8, 0x29, 0xa0, 0x20, 0x64, 0x61, 0x48, 0xec,
	0x9f, 0x4a, 0x70, 0x75, 0xf5, 0x75, 0x25, 0xc3, 0x1d, 0x68, 0x65, 0x4b, 0x68, 0xa5, 0x40, 0x73,
	0x05, 0x3a, 0x97, 0xe5, 0x95, 0x6b, 0x55, 0xd9, 0xaa, 0x95, 0x51, 0xd4, 0xca, 0x76, 0xa1, 0x2d,
	0xdc, 0x52, 0xd0, 0x64, 0x17, 0x76, 0x68, 0x1a, 0xe3, 0x8a, 0x4a, 0x55, 0x6c, 0x9d, 0xe8, 0x2c,
	0xd3, 0xf2, 0x59, 0xa6, 0xf6, 0xaf, 0x15, 0x30, 0xc4, 0x94, 0x5f, 0xf6, 0x4c, 0xdf, 0x5e, 0x61,
	0xe5, 0xb5, 0xe7, 0xcd, 0xd8, 0xe2, 0xe5, 0x42, 0x25, 0xe6, 0x5a, 0x25, 0xd7, 0xc0, 0xcc, 0xa6,
	0x69, 0x82, 0xfa, 0x38, 0x55, 0x1b, 0x81, 0xe2, 0x2c, 0x20, 0x71, 0x77, 0x47, 0xa1, 0x72, 0x23,
	0x50, 0x39, 0x7f, 0xdd, 0x9a, 0x42, 0xe5, 0x46, 0x58, 0x2c, 0x0b, 0x18, 0x7b, 0x95, 0xd2, 0xa8,
	0x5b, 0xcf, 0x3b, 0xaf, 0xf6, 0x42, 0xea, 0x20, 0xe4, 0xe4, 0x25, 0x76, 0xe1, 0x76, 0xe9, 0xae,
	0xe9, 0xe9, 0x9d, 0x50, 0x00, 0xbf, 0xcb, 0x08, 0x45, 0xe6, 0x07, 0xbc, 0xdb, 0x50, 0x0a, 0x68,
	0xa4, 0xc7, 0x45, 0x38, 0xa4, 0x18, 0x70, 0x8c, 0x44, 0xb8, 0xa9, 0xc2, 0x1a, 0x51, 0xe1, 0x79,
	0x16, 0xe5, 0xe1, 0x96, 0x0a, 0x6b, 0xa4, 0xc7, 0x97, 0x76, 0x6b, 0x17, 0xe6, 0x56, 0xf8, 0x73,
	0x9a, 0xf2, 0xd4, 0x9f, 0xd3, 0xb8, 0x7b, 0x55, 0xb3, 0x14, 0xc0, 0x09, 0x8d, 0xed, 0x47, 0xd0,
	0x14, 0x7d, 0x5a, 0xfe, 0x76, 0xec, 0xc2, 0xce, 0x9c, 0x21, 0x2d, 0xb4, 0x5d, 0x6c, 0x9d, 0xc8,
	0xba, 0x05, 0x0d, 0xaa, 0x93, 0x56, 0x9d, 0x83, 0x1c, 0x72, 0x22, 0x7b, 0x08, 0xb5, 0xfc, 0x5c,
	0x3f, 0xff, 0x2d, 0x1f, 0x81, 0x21, 0x8e, 0x59, 0xf9, 0x78, 0xe3, 0xc1, 0xee, 0xbe, 0xba, 0x21,
	0xec, 0xe7, 0x37, 0x84, 0xfd, 0x91, 0xbc, 0x21, 0x78, 0x32, 0xc9, 0xfe, 0xab, 0x0c, 0x3b, 0x23,
	0xdc, 0x3e, 0xa2, 0xff, 0x8f, 0x8f, 0xf2, 0xa2, 0xcc, 0xb5, 0xa2, 0x0a, 0x06, 0xab, 0xae, 0x19,
	0x4c, 0x90, 0xce, 0xb4, 0x8f, 0xca, 0x24, 0x13, 0xdd, 0x91, 0xd5, 0x2b, 0x0f, 0xc9, 0xf5, 0x86,
	0x1d, 0xea, 0x17, 0xdb, 0x01, 0x2e, 0xb6, 0x43, 0x63, 0xd3, 0x0e, 0x1f, 0x42, 0x9b, 0x24, 0x1c,
	0x27, 0x74, 0xd9, 0x37, 0x65, 0xa8, 0x56, 0x01, 0x75, 0x22, 0xfb, 0xef, 0x32, 0xd4, 0x86, 0x01,
	0x63, 0x61, 0x1a, 0xe1, 0x5b, 0xad, 0xf4, 0xfa, 0x6d, 0xac, 0x7a, 0xe9, 0xdb, 0xd8, 0x2d, 0x68,
	0x4c, 0x03, 0x36, 0xc5, 0xc8, 0x17, 0xa5, 0xea, 0xce, 0x80, 0x82, 0x0e, 0x45, 0xf1, 0xd7, 0xc0,
	0x64, 0x3c, 0xe0, 0x28, 0x5b, 0x64, 0x7a, 0x6a, 0xf3, 0x9f, 0xf6, 0xc8, 0xfe, 0xb3, 0x04, 0xe6,
	0x71, 0xfa, 0x1c, 0x13, 0x71, 0x0d, 0x0c, 0xc2, 0x10, 0x19, 0xf3, 0xb9, 0xd8, 0xeb, 0x1e, 0x34,
	0x14, 0xa6, 0x52, 0xee, 0x40, 0x8b, 0xe2, 0x98, 0x22, 0x9b, 0xea, 0x1c, 0x7d, 0xf8, 0x6a, 0x50,
	0x25, 0xad, 0xf3, 0xa9, 0x5c, 0xcc, 0xc7, 0xd8, 0xf4, 0xcc, 0x7a, 0xb1, 0xe6, 0x66, 0xb1, 0xf7,
	0xc1, 0xca, 0x19, 0x88, 0x2b, 0x0c, 0x86, 0x69, 0x12, 0x31, 0xd9, 0x0a, 0xd3, 0xeb, 0xe8, 0x88,
	0x93, 0x8c, 0x14, 0x6e, 0xff, 0x58, 0x81, 0x86, 0xb3, 0xf2, 0xda, 0x5b, 0xfd, 0x73, 0xb0, 0x07,
	0xc0, 0x30, 0xa4, 0xc8, 0xfd, 0xe7, 0xb8, 0xc8, 0xaf, 0xd8, 0x0a, 0x79, 0x8c, 0x0b, 0xd1, 0x1d,
	0x92, 0xf9, 0xaf, 0xa6, 0x84, 0x63, 0x4c, 0x18, 0xd7, 0xe6, 0x69, 0x90, 0xec, 0x59, 0x0e, 0x15,
	0x8e, 0xfc, 0xda, 0x05, 0x47, 0xfe, 0xbf, 0x3c, 0xe3, 0xd7, 0xc0, 0xe4, 0x84, 0xc7, 0xa8, 0x47,
	0x5b, 0x6d, 0x96, 0x47, 0x4d, 0x6b, 0x75, 0xd4, 0xdc, 0xfb, 0x12, 0xae, 0x6e, 0x5c, 0x2a, 0xad,
	0x06, 0xec, 0x9c, 0xb8, 0x8f, 0xdd, 0xa3, 0x67, 0x6e, 0xe7, 0x8a, 0xd5, 0x84, 0xda, 0xe8, 0xb8,
	0xe7, 0xf6, 0x7b, 0x5e, 0xbf, 0x53, 0xb2, 0x76, 0xa0, 0x72, 0x74, 0x3c, 0xec, 0x94, 0x05, 0x3c,
	0xec, 0x8d, 0x46, 0x87, 0x47, 0xfd, 0x41, 0xa7, 0x22, 0x76, 0x47, 0xee, 0xe0, 0xc1, 0xd3, 0x9e,
	0xfb, 0x75, 0xc7, 0xb8, 0xf7, 0x29, 0xbc, 0x73, 0x66, 0xe0, 0xac, 0x16, 0xd4, 0x4f, 0xdc, 0xfe,
	0xe0, 0xd0, 0xe9, 0x0f, 0xfa, 0x9d, 0x2b, 0x56, 0x1d, 0xcc, 0xe1, 0xa3, 0x23, 0x77, 0xd0, 0x29,
	0x89, 0xe5, 0xe0, 0x69, 0xcf, 0x79, 0xd2, 0x29, 0xdf, 0xfb, 0x04, 0x5a, 0x6b, 0x7f, 0x2a, 0xac,
	0x36, 0xc0, 0x89, 0xeb, 0x0d, 0xbe, 0x1a, 0xf4, 0x9e, 0xc8, 0xc7, 0x00, 0xaa, 0x0f, 0xbd, 0x9e,
	0x7b, 0xf8, 0xa8, 0x53, 0x12, 0x6b, 0x6f, 0xf0, 0x85, 0x73, 0xe4, 0x76, 0xca, 0x0f, 0x77, 0xbf,
	0x79, 0x77, 0x82, 0x89, 0xfc, 0xc5, 0x38, 0x28, 0x4e, 0xfe, 0x69, 0x55, 0x62, 0x1f, 0xff, 0x13,
	0x00, 0x00, 0xff, 0xff, 0x0d, 0xeb, 0x57, 0x2f, 0x91, 0x0e, 0x00, 0x00,
}
