// Code generated by protoc-gen-go. DO NOT EDIT.
// source: client_service.proto

package auth_service

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ClientPlatformDetailedResponse struct {
	Id                   string        `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProjectId            string        `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Name                 string        `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Subdomain            string        `protobuf:"bytes,4,opt,name=subdomain,proto3" json:"subdomain,omitempty"`
	Permissions          []*Permission `protobuf:"bytes,5,rep,name=permissions,proto3" json:"permissions,omitempty"`
	Scopes               []*Scope      `protobuf:"bytes,6,rep,name=scopes,proto3" json:"scopes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ClientPlatformDetailedResponse) Reset()         { *m = ClientPlatformDetailedResponse{} }
func (m *ClientPlatformDetailedResponse) String() string { return proto.CompactTextString(m) }
func (*ClientPlatformDetailedResponse) ProtoMessage()    {}
func (*ClientPlatformDetailedResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eee24fc862d835ee, []int{0}
}

func (m *ClientPlatformDetailedResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientPlatformDetailedResponse.Unmarshal(m, b)
}
func (m *ClientPlatformDetailedResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientPlatformDetailedResponse.Marshal(b, m, deterministic)
}
func (m *ClientPlatformDetailedResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientPlatformDetailedResponse.Merge(m, src)
}
func (m *ClientPlatformDetailedResponse) XXX_Size() int {
	return xxx_messageInfo_ClientPlatformDetailedResponse.Size(m)
}
func (m *ClientPlatformDetailedResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientPlatformDetailedResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ClientPlatformDetailedResponse proto.InternalMessageInfo

func (m *ClientPlatformDetailedResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ClientPlatformDetailedResponse) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

func (m *ClientPlatformDetailedResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ClientPlatformDetailedResponse) GetSubdomain() string {
	if m != nil {
		return m.Subdomain
	}
	return ""
}

func (m *ClientPlatformDetailedResponse) GetPermissions() []*Permission {
	if m != nil {
		return m.Permissions
	}
	return nil
}

func (m *ClientPlatformDetailedResponse) GetScopes() []*Scope {
	if m != nil {
		return m.Scopes
	}
	return nil
}

type GetClientMatrixRequest struct {
	ProjectId            string   `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetClientMatrixRequest) Reset()         { *m = GetClientMatrixRequest{} }
func (m *GetClientMatrixRequest) String() string { return proto.CompactTextString(m) }
func (*GetClientMatrixRequest) ProtoMessage()    {}
func (*GetClientMatrixRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eee24fc862d835ee, []int{1}
}

func (m *GetClientMatrixRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetClientMatrixRequest.Unmarshal(m, b)
}
func (m *GetClientMatrixRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetClientMatrixRequest.Marshal(b, m, deterministic)
}
func (m *GetClientMatrixRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetClientMatrixRequest.Merge(m, src)
}
func (m *GetClientMatrixRequest) XXX_Size() int {
	return xxx_messageInfo_GetClientMatrixRequest.Size(m)
}
func (m *GetClientMatrixRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetClientMatrixRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetClientMatrixRequest proto.InternalMessageInfo

func (m *GetClientMatrixRequest) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

type GetClientMatrixResponse struct {
	ClientPlatforms      []*ClientPlatform `protobuf:"bytes,1,rep,name=client_platforms,json=clientPlatforms,proto3" json:"client_platforms,omitempty"`
	ClientTypes          []*ClientType     `protobuf:"bytes,2,rep,name=client_types,json=clientTypes,proto3" json:"client_types,omitempty"`
	Clients              []*Client         `protobuf:"bytes,3,rep,name=clients,proto3" json:"clients,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetClientMatrixResponse) Reset()         { *m = GetClientMatrixResponse{} }
func (m *GetClientMatrixResponse) String() string { return proto.CompactTextString(m) }
func (*GetClientMatrixResponse) ProtoMessage()    {}
func (*GetClientMatrixResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eee24fc862d835ee, []int{2}
}

func (m *GetClientMatrixResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetClientMatrixResponse.Unmarshal(m, b)
}
func (m *GetClientMatrixResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetClientMatrixResponse.Marshal(b, m, deterministic)
}
func (m *GetClientMatrixResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetClientMatrixResponse.Merge(m, src)
}
func (m *GetClientMatrixResponse) XXX_Size() int {
	return xxx_messageInfo_GetClientMatrixResponse.Size(m)
}
func (m *GetClientMatrixResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetClientMatrixResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetClientMatrixResponse proto.InternalMessageInfo

func (m *GetClientMatrixResponse) GetClientPlatforms() []*ClientPlatform {
	if m != nil {
		return m.ClientPlatforms
	}
	return nil
}

func (m *GetClientMatrixResponse) GetClientTypes() []*ClientType {
	if m != nil {
		return m.ClientTypes
	}
	return nil
}

func (m *GetClientMatrixResponse) GetClients() []*Client {
	if m != nil {
		return m.Clients
	}
	return nil
}

type CreateClientPlatformRequest struct {
	ProjectId            string   `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Subdomain            string   `protobuf:"bytes,4,opt,name=subdomain,proto3" json:"subdomain,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateClientPlatformRequest) Reset()         { *m = CreateClientPlatformRequest{} }
func (m *CreateClientPlatformRequest) String() string { return proto.CompactTextString(m) }
func (*CreateClientPlatformRequest) ProtoMessage()    {}
func (*CreateClientPlatformRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eee24fc862d835ee, []int{3}
}

func (m *CreateClientPlatformRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateClientPlatformRequest.Unmarshal(m, b)
}
func (m *CreateClientPlatformRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateClientPlatformRequest.Marshal(b, m, deterministic)
}
func (m *CreateClientPlatformRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateClientPlatformRequest.Merge(m, src)
}
func (m *CreateClientPlatformRequest) XXX_Size() int {
	return xxx_messageInfo_CreateClientPlatformRequest.Size(m)
}
func (m *CreateClientPlatformRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateClientPlatformRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateClientPlatformRequest proto.InternalMessageInfo

func (m *CreateClientPlatformRequest) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

func (m *CreateClientPlatformRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateClientPlatformRequest) GetSubdomain() string {
	if m != nil {
		return m.Subdomain
	}
	return ""
}

type ClientPlatformPrimaryKey struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientPlatformPrimaryKey) Reset()         { *m = ClientPlatformPrimaryKey{} }
func (m *ClientPlatformPrimaryKey) String() string { return proto.CompactTextString(m) }
func (*ClientPlatformPrimaryKey) ProtoMessage()    {}
func (*ClientPlatformPrimaryKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_eee24fc862d835ee, []int{4}
}

func (m *ClientPlatformPrimaryKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientPlatformPrimaryKey.Unmarshal(m, b)
}
func (m *ClientPlatformPrimaryKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientPlatformPrimaryKey.Marshal(b, m, deterministic)
}
func (m *ClientPlatformPrimaryKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientPlatformPrimaryKey.Merge(m, src)
}
func (m *ClientPlatformPrimaryKey) XXX_Size() int {
	return xxx_messageInfo_ClientPlatformPrimaryKey.Size(m)
}
func (m *ClientPlatformPrimaryKey) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientPlatformPrimaryKey.DiscardUnknown(m)
}

var xxx_messageInfo_ClientPlatformPrimaryKey proto.InternalMessageInfo

func (m *ClientPlatformPrimaryKey) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetClientPlatformListRequest struct {
	Limit                int32    `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               int32    `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Search               string   `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	ProjectId            string   `protobuf:"bytes,4,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetClientPlatformListRequest) Reset()         { *m = GetClientPlatformListRequest{} }
func (m *GetClientPlatformListRequest) String() string { return proto.CompactTextString(m) }
func (*GetClientPlatformListRequest) ProtoMessage()    {}
func (*GetClientPlatformListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eee24fc862d835ee, []int{5}
}

func (m *GetClientPlatformListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetClientPlatformListRequest.Unmarshal(m, b)
}
func (m *GetClientPlatformListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetClientPlatformListRequest.Marshal(b, m, deterministic)
}
func (m *GetClientPlatformListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetClientPlatformListRequest.Merge(m, src)
}
func (m *GetClientPlatformListRequest) XXX_Size() int {
	return xxx_messageInfo_GetClientPlatformListRequest.Size(m)
}
func (m *GetClientPlatformListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetClientPlatformListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetClientPlatformListRequest proto.InternalMessageInfo

func (m *GetClientPlatformListRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetClientPlatformListRequest) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *GetClientPlatformListRequest) GetSearch() string {
	if m != nil {
		return m.Search
	}
	return ""
}

func (m *GetClientPlatformListRequest) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

type GetClientPlatformListResponse struct {
	Count                int32             `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	ClientPlatforms      []*ClientPlatform `protobuf:"bytes,2,rep,name=client_platforms,json=clientPlatforms,proto3" json:"client_platforms,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetClientPlatformListResponse) Reset()         { *m = GetClientPlatformListResponse{} }
func (m *GetClientPlatformListResponse) String() string { return proto.CompactTextString(m) }
func (*GetClientPlatformListResponse) ProtoMessage()    {}
func (*GetClientPlatformListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eee24fc862d835ee, []int{6}
}

func (m *GetClientPlatformListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetClientPlatformListResponse.Unmarshal(m, b)
}
func (m *GetClientPlatformListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetClientPlatformListResponse.Marshal(b, m, deterministic)
}
func (m *GetClientPlatformListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetClientPlatformListResponse.Merge(m, src)
}
func (m *GetClientPlatformListResponse) XXX_Size() int {
	return xxx_messageInfo_GetClientPlatformListResponse.Size(m)
}
func (m *GetClientPlatformListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetClientPlatformListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetClientPlatformListResponse proto.InternalMessageInfo

func (m *GetClientPlatformListResponse) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *GetClientPlatformListResponse) GetClientPlatforms() []*ClientPlatform {
	if m != nil {
		return m.ClientPlatforms
	}
	return nil
}

type UpdateClientPlatformRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Subdomain            string   `protobuf:"bytes,4,opt,name=subdomain,proto3" json:"subdomain,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateClientPlatformRequest) Reset()         { *m = UpdateClientPlatformRequest{} }
func (m *UpdateClientPlatformRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateClientPlatformRequest) ProtoMessage()    {}
func (*UpdateClientPlatformRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eee24fc862d835ee, []int{7}
}

func (m *UpdateClientPlatformRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateClientPlatformRequest.Unmarshal(m, b)
}
func (m *UpdateClientPlatformRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateClientPlatformRequest.Marshal(b, m, deterministic)
}
func (m *UpdateClientPlatformRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateClientPlatformRequest.Merge(m, src)
}
func (m *UpdateClientPlatformRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateClientPlatformRequest.Size(m)
}
func (m *UpdateClientPlatformRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateClientPlatformRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateClientPlatformRequest proto.InternalMessageInfo

func (m *UpdateClientPlatformRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateClientPlatformRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateClientPlatformRequest) GetSubdomain() string {
	if m != nil {
		return m.Subdomain
	}
	return ""
}

type CreateClientTypeRequest struct {
	Name                 string            `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ConfirmBy            ConfirmStrategies `protobuf:"varint,3,opt,name=confirm_by,json=confirmBy,proto3,enum=auth_service.ConfirmStrategies" json:"confirm_by,omitempty"`
	SelfRegister         bool              `protobuf:"varint,4,opt,name=self_register,json=selfRegister,proto3" json:"self_register,omitempty"`
	SelfRecover          bool              `protobuf:"varint,5,opt,name=self_recover,json=selfRecover,proto3" json:"self_recover,omitempty"`
	ProjectId            string            `protobuf:"bytes,6,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CreateClientTypeRequest) Reset()         { *m = CreateClientTypeRequest{} }
func (m *CreateClientTypeRequest) String() string { return proto.CompactTextString(m) }
func (*CreateClientTypeRequest) ProtoMessage()    {}
func (*CreateClientTypeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eee24fc862d835ee, []int{8}
}

func (m *CreateClientTypeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateClientTypeRequest.Unmarshal(m, b)
}
func (m *CreateClientTypeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateClientTypeRequest.Marshal(b, m, deterministic)
}
func (m *CreateClientTypeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateClientTypeRequest.Merge(m, src)
}
func (m *CreateClientTypeRequest) XXX_Size() int {
	return xxx_messageInfo_CreateClientTypeRequest.Size(m)
}
func (m *CreateClientTypeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateClientTypeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateClientTypeRequest proto.InternalMessageInfo

func (m *CreateClientTypeRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateClientTypeRequest) GetConfirmBy() ConfirmStrategies {
	if m != nil {
		return m.ConfirmBy
	}
	return ConfirmStrategies_UNDECIDED
}

func (m *CreateClientTypeRequest) GetSelfRegister() bool {
	if m != nil {
		return m.SelfRegister
	}
	return false
}

func (m *CreateClientTypeRequest) GetSelfRecover() bool {
	if m != nil {
		return m.SelfRecover
	}
	return false
}

func (m *CreateClientTypeRequest) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

type ClientTypePrimaryKey struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientTypePrimaryKey) Reset()         { *m = ClientTypePrimaryKey{} }
func (m *ClientTypePrimaryKey) String() string { return proto.CompactTextString(m) }
func (*ClientTypePrimaryKey) ProtoMessage()    {}
func (*ClientTypePrimaryKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_eee24fc862d835ee, []int{9}
}

func (m *ClientTypePrimaryKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientTypePrimaryKey.Unmarshal(m, b)
}
func (m *ClientTypePrimaryKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientTypePrimaryKey.Marshal(b, m, deterministic)
}
func (m *ClientTypePrimaryKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientTypePrimaryKey.Merge(m, src)
}
func (m *ClientTypePrimaryKey) XXX_Size() int {
	return xxx_messageInfo_ClientTypePrimaryKey.Size(m)
}
func (m *ClientTypePrimaryKey) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientTypePrimaryKey.DiscardUnknown(m)
}

var xxx_messageInfo_ClientTypePrimaryKey proto.InternalMessageInfo

func (m *ClientTypePrimaryKey) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type CompleteClientType struct {
	ClientType           *ClientType      `protobuf:"bytes,1,opt,name=client_type,json=clientType,proto3" json:"client_type,omitempty"`
	Relations            []*Relation      `protobuf:"bytes,2,rep,name=relations,proto3" json:"relations,omitempty"`
	UserInfoFields       []*UserInfoField `protobuf:"bytes,3,rep,name=user_info_fields,json=userInfoFields,proto3" json:"user_info_fields,omitempty"`
	Roles                []*Role          `protobuf:"bytes,4,rep,name=roles,proto3" json:"roles,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *CompleteClientType) Reset()         { *m = CompleteClientType{} }
func (m *CompleteClientType) String() string { return proto.CompactTextString(m) }
func (*CompleteClientType) ProtoMessage()    {}
func (*CompleteClientType) Descriptor() ([]byte, []int) {
	return fileDescriptor_eee24fc862d835ee, []int{10}
}

func (m *CompleteClientType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CompleteClientType.Unmarshal(m, b)
}
func (m *CompleteClientType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CompleteClientType.Marshal(b, m, deterministic)
}
func (m *CompleteClientType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CompleteClientType.Merge(m, src)
}
func (m *CompleteClientType) XXX_Size() int {
	return xxx_messageInfo_CompleteClientType.Size(m)
}
func (m *CompleteClientType) XXX_DiscardUnknown() {
	xxx_messageInfo_CompleteClientType.DiscardUnknown(m)
}

var xxx_messageInfo_CompleteClientType proto.InternalMessageInfo

func (m *CompleteClientType) GetClientType() *ClientType {
	if m != nil {
		return m.ClientType
	}
	return nil
}

func (m *CompleteClientType) GetRelations() []*Relation {
	if m != nil {
		return m.Relations
	}
	return nil
}

func (m *CompleteClientType) GetUserInfoFields() []*UserInfoField {
	if m != nil {
		return m.UserInfoFields
	}
	return nil
}

func (m *CompleteClientType) GetRoles() []*Role {
	if m != nil {
		return m.Roles
	}
	return nil
}

type GetClientTypeListRequest struct {
	Limit                int32    `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               int32    `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Search               string   `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	ProjectId            string   `protobuf:"bytes,4,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetClientTypeListRequest) Reset()         { *m = GetClientTypeListRequest{} }
func (m *GetClientTypeListRequest) String() string { return proto.CompactTextString(m) }
func (*GetClientTypeListRequest) ProtoMessage()    {}
func (*GetClientTypeListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eee24fc862d835ee, []int{11}
}

func (m *GetClientTypeListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetClientTypeListRequest.Unmarshal(m, b)
}
func (m *GetClientTypeListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetClientTypeListRequest.Marshal(b, m, deterministic)
}
func (m *GetClientTypeListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetClientTypeListRequest.Merge(m, src)
}
func (m *GetClientTypeListRequest) XXX_Size() int {
	return xxx_messageInfo_GetClientTypeListRequest.Size(m)
}
func (m *GetClientTypeListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetClientTypeListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetClientTypeListRequest proto.InternalMessageInfo

func (m *GetClientTypeListRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetClientTypeListRequest) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *GetClientTypeListRequest) GetSearch() string {
	if m != nil {
		return m.Search
	}
	return ""
}

func (m *GetClientTypeListRequest) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

type GetClientTypeListResponse struct {
	Count                int32         `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	ClientTypes          []*ClientType `protobuf:"bytes,2,rep,name=client_types,json=clientTypes,proto3" json:"client_types,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetClientTypeListResponse) Reset()         { *m = GetClientTypeListResponse{} }
func (m *GetClientTypeListResponse) String() string { return proto.CompactTextString(m) }
func (*GetClientTypeListResponse) ProtoMessage()    {}
func (*GetClientTypeListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eee24fc862d835ee, []int{12}
}

func (m *GetClientTypeListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetClientTypeListResponse.Unmarshal(m, b)
}
func (m *GetClientTypeListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetClientTypeListResponse.Marshal(b, m, deterministic)
}
func (m *GetClientTypeListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetClientTypeListResponse.Merge(m, src)
}
func (m *GetClientTypeListResponse) XXX_Size() int {
	return xxx_messageInfo_GetClientTypeListResponse.Size(m)
}
func (m *GetClientTypeListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetClientTypeListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetClientTypeListResponse proto.InternalMessageInfo

func (m *GetClientTypeListResponse) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *GetClientTypeListResponse) GetClientTypes() []*ClientType {
	if m != nil {
		return m.ClientTypes
	}
	return nil
}

type UpdateClientTypeRequest struct {
	Id                   string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string            `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ConfirmBy            ConfirmStrategies `protobuf:"varint,3,opt,name=confirm_by,json=confirmBy,proto3,enum=auth_service.ConfirmStrategies" json:"confirm_by,omitempty"`
	SelfRegister         bool              `protobuf:"varint,4,opt,name=self_register,json=selfRegister,proto3" json:"self_register,omitempty"`
	SelfRecover          bool              `protobuf:"varint,5,opt,name=self_recover,json=selfRecover,proto3" json:"self_recover,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *UpdateClientTypeRequest) Reset()         { *m = UpdateClientTypeRequest{} }
func (m *UpdateClientTypeRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateClientTypeRequest) ProtoMessage()    {}
func (*UpdateClientTypeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eee24fc862d835ee, []int{13}
}

func (m *UpdateClientTypeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateClientTypeRequest.Unmarshal(m, b)
}
func (m *UpdateClientTypeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateClientTypeRequest.Marshal(b, m, deterministic)
}
func (m *UpdateClientTypeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateClientTypeRequest.Merge(m, src)
}
func (m *UpdateClientTypeRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateClientTypeRequest.Size(m)
}
func (m *UpdateClientTypeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateClientTypeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateClientTypeRequest proto.InternalMessageInfo

func (m *UpdateClientTypeRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateClientTypeRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateClientTypeRequest) GetConfirmBy() ConfirmStrategies {
	if m != nil {
		return m.ConfirmBy
	}
	return ConfirmStrategies_UNDECIDED
}

func (m *UpdateClientTypeRequest) GetSelfRegister() bool {
	if m != nil {
		return m.SelfRegister
	}
	return false
}

func (m *UpdateClientTypeRequest) GetSelfRecover() bool {
	if m != nil {
		return m.SelfRecover
	}
	return false
}

type AddClientRequest struct {
	ClientPlatformId     string          `protobuf:"bytes,1,opt,name=client_platform_id,json=clientPlatformId,proto3" json:"client_platform_id,omitempty"`
	ClientTypeId         string          `protobuf:"bytes,2,opt,name=client_type_id,json=clientTypeId,proto3" json:"client_type_id,omitempty"`
	LoginStrategy        LoginStrategies `protobuf:"varint,3,opt,name=login_strategy,json=loginStrategy,proto3,enum=auth_service.LoginStrategies" json:"login_strategy,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *AddClientRequest) Reset()         { *m = AddClientRequest{} }
func (m *AddClientRequest) String() string { return proto.CompactTextString(m) }
func (*AddClientRequest) ProtoMessage()    {}
func (*AddClientRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eee24fc862d835ee, []int{14}
}

func (m *AddClientRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddClientRequest.Unmarshal(m, b)
}
func (m *AddClientRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddClientRequest.Marshal(b, m, deterministic)
}
func (m *AddClientRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddClientRequest.Merge(m, src)
}
func (m *AddClientRequest) XXX_Size() int {
	return xxx_messageInfo_AddClientRequest.Size(m)
}
func (m *AddClientRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddClientRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddClientRequest proto.InternalMessageInfo

func (m *AddClientRequest) GetClientPlatformId() string {
	if m != nil {
		return m.ClientPlatformId
	}
	return ""
}

func (m *AddClientRequest) GetClientTypeId() string {
	if m != nil {
		return m.ClientTypeId
	}
	return ""
}

func (m *AddClientRequest) GetLoginStrategy() LoginStrategies {
	if m != nil {
		return m.LoginStrategy
	}
	return LoginStrategies_UNKNOWN
}

type UpdateClientRequest struct {
	ClientPlatformId     string          `protobuf:"bytes,1,opt,name=client_platform_id,json=clientPlatformId,proto3" json:"client_platform_id,omitempty"`
	ClientTypeId         string          `protobuf:"bytes,2,opt,name=client_type_id,json=clientTypeId,proto3" json:"client_type_id,omitempty"`
	LoginStrategy        LoginStrategies `protobuf:"varint,3,opt,name=login_strategy,json=loginStrategy,proto3,enum=auth_service.LoginStrategies" json:"login_strategy,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *UpdateClientRequest) Reset()         { *m = UpdateClientRequest{} }
func (m *UpdateClientRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateClientRequest) ProtoMessage()    {}
func (*UpdateClientRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eee24fc862d835ee, []int{15}
}

func (m *UpdateClientRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateClientRequest.Unmarshal(m, b)
}
func (m *UpdateClientRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateClientRequest.Marshal(b, m, deterministic)
}
func (m *UpdateClientRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateClientRequest.Merge(m, src)
}
func (m *UpdateClientRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateClientRequest.Size(m)
}
func (m *UpdateClientRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateClientRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateClientRequest proto.InternalMessageInfo

func (m *UpdateClientRequest) GetClientPlatformId() string {
	if m != nil {
		return m.ClientPlatformId
	}
	return ""
}

func (m *UpdateClientRequest) GetClientTypeId() string {
	if m != nil {
		return m.ClientTypeId
	}
	return ""
}

func (m *UpdateClientRequest) GetLoginStrategy() LoginStrategies {
	if m != nil {
		return m.LoginStrategy
	}
	return LoginStrategies_UNKNOWN
}

type ClientPrimaryKey struct {
	ClientPlatformId     string   `protobuf:"bytes,1,opt,name=client_platform_id,json=clientPlatformId,proto3" json:"client_platform_id,omitempty"`
	ClientTypeId         string   `protobuf:"bytes,2,opt,name=client_type_id,json=clientTypeId,proto3" json:"client_type_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientPrimaryKey) Reset()         { *m = ClientPrimaryKey{} }
func (m *ClientPrimaryKey) String() string { return proto.CompactTextString(m) }
func (*ClientPrimaryKey) ProtoMessage()    {}
func (*ClientPrimaryKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_eee24fc862d835ee, []int{16}
}

func (m *ClientPrimaryKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientPrimaryKey.Unmarshal(m, b)
}
func (m *ClientPrimaryKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientPrimaryKey.Marshal(b, m, deterministic)
}
func (m *ClientPrimaryKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientPrimaryKey.Merge(m, src)
}
func (m *ClientPrimaryKey) XXX_Size() int {
	return xxx_messageInfo_ClientPrimaryKey.Size(m)
}
func (m *ClientPrimaryKey) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientPrimaryKey.DiscardUnknown(m)
}

var xxx_messageInfo_ClientPrimaryKey proto.InternalMessageInfo

func (m *ClientPrimaryKey) GetClientPlatformId() string {
	if m != nil {
		return m.ClientPlatformId
	}
	return ""
}

func (m *ClientPrimaryKey) GetClientTypeId() string {
	if m != nil {
		return m.ClientTypeId
	}
	return ""
}

type GetClientListRequest struct {
	Limit                int32    `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               int32    `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Search               string   `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	ProjectId            string   `protobuf:"bytes,4,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetClientListRequest) Reset()         { *m = GetClientListRequest{} }
func (m *GetClientListRequest) String() string { return proto.CompactTextString(m) }
func (*GetClientListRequest) ProtoMessage()    {}
func (*GetClientListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eee24fc862d835ee, []int{17}
}

func (m *GetClientListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetClientListRequest.Unmarshal(m, b)
}
func (m *GetClientListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetClientListRequest.Marshal(b, m, deterministic)
}
func (m *GetClientListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetClientListRequest.Merge(m, src)
}
func (m *GetClientListRequest) XXX_Size() int {
	return xxx_messageInfo_GetClientListRequest.Size(m)
}
func (m *GetClientListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetClientListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetClientListRequest proto.InternalMessageInfo

func (m *GetClientListRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetClientListRequest) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *GetClientListRequest) GetSearch() string {
	if m != nil {
		return m.Search
	}
	return ""
}

func (m *GetClientListRequest) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

type GetClientListResponse struct {
	Count                int32     `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Clients              []*Client `protobuf:"bytes,2,rep,name=clients,proto3" json:"clients,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetClientListResponse) Reset()         { *m = GetClientListResponse{} }
func (m *GetClientListResponse) String() string { return proto.CompactTextString(m) }
func (*GetClientListResponse) ProtoMessage()    {}
func (*GetClientListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eee24fc862d835ee, []int{18}
}

func (m *GetClientListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetClientListResponse.Unmarshal(m, b)
}
func (m *GetClientListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetClientListResponse.Marshal(b, m, deterministic)
}
func (m *GetClientListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetClientListResponse.Merge(m, src)
}
func (m *GetClientListResponse) XXX_Size() int {
	return xxx_messageInfo_GetClientListResponse.Size(m)
}
func (m *GetClientListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetClientListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetClientListResponse proto.InternalMessageInfo

func (m *GetClientListResponse) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *GetClientListResponse) GetClients() []*Client {
	if m != nil {
		return m.Clients
	}
	return nil
}

type AddRelationRequest struct {
	ClientTypeId         string        `protobuf:"bytes,2,opt,name=client_type_id,json=clientTypeId,proto3" json:"client_type_id,omitempty"`
	Type                 RelationTypes `protobuf:"varint,3,opt,name=type,proto3,enum=auth_service.RelationTypes" json:"type,omitempty"`
	Name                 string        `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Description          string        `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *AddRelationRequest) Reset()         { *m = AddRelationRequest{} }
func (m *AddRelationRequest) String() string { return proto.CompactTextString(m) }
func (*AddRelationRequest) ProtoMessage()    {}
func (*AddRelationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eee24fc862d835ee, []int{19}
}

func (m *AddRelationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRelationRequest.Unmarshal(m, b)
}
func (m *AddRelationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRelationRequest.Marshal(b, m, deterministic)
}
func (m *AddRelationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRelationRequest.Merge(m, src)
}
func (m *AddRelationRequest) XXX_Size() int {
	return xxx_messageInfo_AddRelationRequest.Size(m)
}
func (m *AddRelationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRelationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddRelationRequest proto.InternalMessageInfo

func (m *AddRelationRequest) GetClientTypeId() string {
	if m != nil {
		return m.ClientTypeId
	}
	return ""
}

func (m *AddRelationRequest) GetType() RelationTypes {
	if m != nil {
		return m.Type
	}
	return RelationTypes_UNREVEALED
}

func (m *AddRelationRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AddRelationRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type UpdateRelationRequest struct {
	Id                   string        `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ClientTypeId         string        `protobuf:"bytes,2,opt,name=client_type_id,json=clientTypeId,proto3" json:"client_type_id,omitempty"`
	Type                 RelationTypes `protobuf:"varint,3,opt,name=type,proto3,enum=auth_service.RelationTypes" json:"type,omitempty"`
	Name                 string        `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Description          string        `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *UpdateRelationRequest) Reset()         { *m = UpdateRelationRequest{} }
func (m *UpdateRelationRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRelationRequest) ProtoMessage()    {}
func (*UpdateRelationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eee24fc862d835ee, []int{20}
}

func (m *UpdateRelationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRelationRequest.Unmarshal(m, b)
}
func (m *UpdateRelationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRelationRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRelationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRelationRequest.Merge(m, src)
}
func (m *UpdateRelationRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRelationRequest.Size(m)
}
func (m *UpdateRelationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRelationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRelationRequest proto.InternalMessageInfo

func (m *UpdateRelationRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateRelationRequest) GetClientTypeId() string {
	if m != nil {
		return m.ClientTypeId
	}
	return ""
}

func (m *UpdateRelationRequest) GetType() RelationTypes {
	if m != nil {
		return m.Type
	}
	return RelationTypes_UNREVEALED
}

func (m *UpdateRelationRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateRelationRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type RelationPrimaryKey struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RelationPrimaryKey) Reset()         { *m = RelationPrimaryKey{} }
func (m *RelationPrimaryKey) String() string { return proto.CompactTextString(m) }
func (*RelationPrimaryKey) ProtoMessage()    {}
func (*RelationPrimaryKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_eee24fc862d835ee, []int{21}
}

func (m *RelationPrimaryKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RelationPrimaryKey.Unmarshal(m, b)
}
func (m *RelationPrimaryKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RelationPrimaryKey.Marshal(b, m, deterministic)
}
func (m *RelationPrimaryKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RelationPrimaryKey.Merge(m, src)
}
func (m *RelationPrimaryKey) XXX_Size() int {
	return xxx_messageInfo_RelationPrimaryKey.Size(m)
}
func (m *RelationPrimaryKey) XXX_DiscardUnknown() {
	xxx_messageInfo_RelationPrimaryKey.DiscardUnknown(m)
}

var xxx_messageInfo_RelationPrimaryKey proto.InternalMessageInfo

func (m *RelationPrimaryKey) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type AddUserInfoFieldRequest struct {
	ClientTypeId         string   `protobuf:"bytes,2,opt,name=client_type_id,json=clientTypeId,proto3" json:"client_type_id,omitempty"`
	FieldName            string   `protobuf:"bytes,3,opt,name=field_name,json=fieldName,proto3" json:"field_name,omitempty"`
	FieldType            string   `protobuf:"bytes,4,opt,name=field_type,json=fieldType,proto3" json:"field_type,omitempty"`
	DataType             string   `protobuf:"bytes,5,opt,name=data_type,json=dataType,proto3" json:"data_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddUserInfoFieldRequest) Reset()         { *m = AddUserInfoFieldRequest{} }
func (m *AddUserInfoFieldRequest) String() string { return proto.CompactTextString(m) }
func (*AddUserInfoFieldRequest) ProtoMessage()    {}
func (*AddUserInfoFieldRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eee24fc862d835ee, []int{22}
}

func (m *AddUserInfoFieldRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddUserInfoFieldRequest.Unmarshal(m, b)
}
func (m *AddUserInfoFieldRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddUserInfoFieldRequest.Marshal(b, m, deterministic)
}
func (m *AddUserInfoFieldRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddUserInfoFieldRequest.Merge(m, src)
}
func (m *AddUserInfoFieldRequest) XXX_Size() int {
	return xxx_messageInfo_AddUserInfoFieldRequest.Size(m)
}
func (m *AddUserInfoFieldRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddUserInfoFieldRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddUserInfoFieldRequest proto.InternalMessageInfo

func (m *AddUserInfoFieldRequest) GetClientTypeId() string {
	if m != nil {
		return m.ClientTypeId
	}
	return ""
}

func (m *AddUserInfoFieldRequest) GetFieldName() string {
	if m != nil {
		return m.FieldName
	}
	return ""
}

func (m *AddUserInfoFieldRequest) GetFieldType() string {
	if m != nil {
		return m.FieldType
	}
	return ""
}

func (m *AddUserInfoFieldRequest) GetDataType() string {
	if m != nil {
		return m.DataType
	}
	return ""
}

type UpdateUserInfoFieldRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ClientTypeId         string   `protobuf:"bytes,2,opt,name=client_type_id,json=clientTypeId,proto3" json:"client_type_id,omitempty"`
	FieldName            string   `protobuf:"bytes,3,opt,name=field_name,json=fieldName,proto3" json:"field_name,omitempty"`
	FieldType            string   `protobuf:"bytes,4,opt,name=field_type,json=fieldType,proto3" json:"field_type,omitempty"`
	DataType             string   `protobuf:"bytes,5,opt,name=data_type,json=dataType,proto3" json:"data_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserInfoFieldRequest) Reset()         { *m = UpdateUserInfoFieldRequest{} }
func (m *UpdateUserInfoFieldRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUserInfoFieldRequest) ProtoMessage()    {}
func (*UpdateUserInfoFieldRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eee24fc862d835ee, []int{23}
}

func (m *UpdateUserInfoFieldRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserInfoFieldRequest.Unmarshal(m, b)
}
func (m *UpdateUserInfoFieldRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserInfoFieldRequest.Marshal(b, m, deterministic)
}
func (m *UpdateUserInfoFieldRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserInfoFieldRequest.Merge(m, src)
}
func (m *UpdateUserInfoFieldRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUserInfoFieldRequest.Size(m)
}
func (m *UpdateUserInfoFieldRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserInfoFieldRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserInfoFieldRequest proto.InternalMessageInfo

func (m *UpdateUserInfoFieldRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateUserInfoFieldRequest) GetClientTypeId() string {
	if m != nil {
		return m.ClientTypeId
	}
	return ""
}

func (m *UpdateUserInfoFieldRequest) GetFieldName() string {
	if m != nil {
		return m.FieldName
	}
	return ""
}

func (m *UpdateUserInfoFieldRequest) GetFieldType() string {
	if m != nil {
		return m.FieldType
	}
	return ""
}

func (m *UpdateUserInfoFieldRequest) GetDataType() string {
	if m != nil {
		return m.DataType
	}
	return ""
}

type UserInfoFieldPrimaryKey struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfoFieldPrimaryKey) Reset()         { *m = UserInfoFieldPrimaryKey{} }
func (m *UserInfoFieldPrimaryKey) String() string { return proto.CompactTextString(m) }
func (*UserInfoFieldPrimaryKey) ProtoMessage()    {}
func (*UserInfoFieldPrimaryKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_eee24fc862d835ee, []int{24}
}

func (m *UserInfoFieldPrimaryKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfoFieldPrimaryKey.Unmarshal(m, b)
}
func (m *UserInfoFieldPrimaryKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfoFieldPrimaryKey.Marshal(b, m, deterministic)
}
func (m *UserInfoFieldPrimaryKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfoFieldPrimaryKey.Merge(m, src)
}
func (m *UserInfoFieldPrimaryKey) XXX_Size() int {
	return xxx_messageInfo_UserInfoFieldPrimaryKey.Size(m)
}
func (m *UserInfoFieldPrimaryKey) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfoFieldPrimaryKey.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfoFieldPrimaryKey proto.InternalMessageInfo

func (m *UserInfoFieldPrimaryKey) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*ClientPlatformDetailedResponse)(nil), "auth_service.ClientPlatformDetailedResponse")
	proto.RegisterType((*GetClientMatrixRequest)(nil), "auth_service.GetClientMatrixRequest")
	proto.RegisterType((*GetClientMatrixResponse)(nil), "auth_service.GetClientMatrixResponse")
	proto.RegisterType((*CreateClientPlatformRequest)(nil), "auth_service.CreateClientPlatformRequest")
	proto.RegisterType((*ClientPlatformPrimaryKey)(nil), "auth_service.ClientPlatformPrimaryKey")
	proto.RegisterType((*GetClientPlatformListRequest)(nil), "auth_service.GetClientPlatformListRequest")
	proto.RegisterType((*GetClientPlatformListResponse)(nil), "auth_service.GetClientPlatformListResponse")
	proto.RegisterType((*UpdateClientPlatformRequest)(nil), "auth_service.UpdateClientPlatformRequest")
	proto.RegisterType((*CreateClientTypeRequest)(nil), "auth_service.CreateClientTypeRequest")
	proto.RegisterType((*ClientTypePrimaryKey)(nil), "auth_service.ClientTypePrimaryKey")
	proto.RegisterType((*CompleteClientType)(nil), "auth_service.CompleteClientType")
	proto.RegisterType((*GetClientTypeListRequest)(nil), "auth_service.GetClientTypeListRequest")
	proto.RegisterType((*GetClientTypeListResponse)(nil), "auth_service.GetClientTypeListResponse")
	proto.RegisterType((*UpdateClientTypeRequest)(nil), "auth_service.UpdateClientTypeRequest")
	proto.RegisterType((*AddClientRequest)(nil), "auth_service.AddClientRequest")
	proto.RegisterType((*UpdateClientRequest)(nil), "auth_service.UpdateClientRequest")
	proto.RegisterType((*ClientPrimaryKey)(nil), "auth_service.ClientPrimaryKey")
	proto.RegisterType((*GetClientListRequest)(nil), "auth_service.GetClientListRequest")
	proto.RegisterType((*GetClientListResponse)(nil), "auth_service.GetClientListResponse")
	proto.RegisterType((*AddRelationRequest)(nil), "auth_service.AddRelationRequest")
	proto.RegisterType((*UpdateRelationRequest)(nil), "auth_service.UpdateRelationRequest")
	proto.RegisterType((*RelationPrimaryKey)(nil), "auth_service.RelationPrimaryKey")
	proto.RegisterType((*AddUserInfoFieldRequest)(nil), "auth_service.AddUserInfoFieldRequest")
	proto.RegisterType((*UpdateUserInfoFieldRequest)(nil), "auth_service.UpdateUserInfoFieldRequest")
	proto.RegisterType((*UserInfoFieldPrimaryKey)(nil), "auth_service.UserInfoFieldPrimaryKey")
}

func init() { proto.RegisterFile("client_service.proto", fileDescriptor_eee24fc862d835ee) }

var fileDescriptor_eee24fc862d835ee = []byte{
	// 1326 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x58, 0xdd, 0x6e, 0xe3, 0xc4,
	0x17, 0x8f, 0xb3, 0x49, 0xff, 0x9b, 0x93, 0x34, 0xcd, 0x7f, 0x9a, 0x36, 0xc6, 0x69, 0x97, 0xee,
	0xb4, 0x5b, 0xba, 0x1f, 0x4a, 0xa5, 0x82, 0x84, 0x00, 0x09, 0xa9, 0x1f, 0xbb, 0xab, 0x88, 0x02,
	0x95, 0x4b, 0xa5, 0xd5, 0xae, 0x20, 0xb8, 0xf1, 0x24, 0x6b, 0xe4, 0xd8, 0xc6, 0xe3, 0x14, 0x22,
	0x24, 0xb8, 0xe0, 0x2d, 0xb8, 0xe3, 0x1e, 0xc4, 0x0d, 0xaf, 0xc0, 0x35, 0x37, 0xdc, 0xf0, 0x0a,
	0x3c, 0x00, 0xd7, 0xc8, 0xe3, 0x8f, 0x8c, 0xa7, 0xb6, 0x93, 0xed, 0x6a, 0x57, 0xbd, 0xf3, 0x9c,
	0x39, 0xe7, 0xcc, 0xf9, 0x9e, 0xdf, 0x18, 0x9a, 0x7d, 0xd3, 0x20, 0x96, 0xd7, 0xa3, 0xc4, 0xbd,
	0x30, 0xfa, 0xa4, 0xe3, 0xb8, 0xb6, 0x67, 0xa3, 0x9a, 0x36, 0xf6, 0x9e, 0x47, 0x34, 0x05, 0xfc,
	0x55, 0xb0, 0xa3, 0xb4, 0x87, 0xb6, 0x3d, 0x34, 0xc9, 0x2e, 0x5b, 0x9d, 0x8f, 0x07, 0xbb, 0x64,
	0xe4, 0x78, 0x93, 0x60, 0x13, 0xff, 0x23, 0xc1, 0xad, 0x43, 0xa6, 0xef, 0xc4, 0xd4, 0xbc, 0x81,
	0xed, 0x8e, 0x8e, 0x88, 0xa7, 0x19, 0x26, 0xd1, 0x55, 0x42, 0x1d, 0xdb, 0xa2, 0x04, 0xd5, 0xa1,
	0x68, 0xe8, 0xb2, 0xb4, 0x21, 0xed, 0x54, 0xd4, 0xa2, 0xa1, 0xa3, 0x75, 0x00, 0xc7, 0xb5, 0xbf,
	0x22, 0x7d, 0xaf, 0x67, 0xe8, 0x72, 0x91, 0xd1, 0x2b, 0x21, 0xa5, 0xab, 0x23, 0x04, 0x25, 0x4b,
	0x1b, 0x11, 0xf9, 0x06, 0xdb, 0x60, 0xdf, 0x68, 0x0d, 0x2a, 0x74, 0x7c, 0xae, 0xdb, 0x23, 0xcd,
	0xb0, 0xe4, 0x52, 0x20, 0x11, 0x13, 0xd0, 0xfb, 0x50, 0x75, 0x88, 0x3b, 0x32, 0x28, 0x35, 0x6c,
	0x8b, 0xca, 0xe5, 0x8d, 0x1b, 0x3b, 0xd5, 0x3d, 0xb9, 0xc3, 0x3b, 0xd4, 0x39, 0x89, 0x19, 0x54,
	0x9e, 0x19, 0xdd, 0x87, 0x05, 0xda, 0xb7, 0x1d, 0x42, 0xe5, 0x05, 0x26, 0xb6, 0x9c, 0x14, 0x3b,
	0xf5, 0xf7, 0xd4, 0x90, 0x05, 0xbf, 0x0b, 0xab, 0x8f, 0x89, 0x17, 0xb8, 0xfb, 0xb1, 0xe6, 0xb9,
	0xc6, 0xb7, 0x2a, 0xf9, 0x7a, 0x4c, 0xa8, 0x27, 0xf8, 0x24, 0x09, 0x3e, 0xe1, 0x3f, 0x25, 0x68,
	0x5d, 0x92, 0x0c, 0xc3, 0xf3, 0x18, 0x1a, 0x61, 0x42, 0x9c, 0x30, 0x82, 0x54, 0x96, 0x98, 0x2d,
	0x6b, 0x49, 0x5b, 0x92, 0x61, 0x56, 0x97, 0xfa, 0x89, 0x35, 0x45, 0x1f, 0x40, 0x2d, 0x54, 0xe4,
	0x4d, 0x7c, 0x87, 0x8a, 0x69, 0x71, 0x08, 0x94, 0x7c, 0x36, 0x71, 0x88, 0x5a, 0xed, 0xc7, 0xdf,
	0x14, 0x75, 0xe0, 0x7f, 0xc1, 0x92, 0xca, 0x37, 0x98, 0x5c, 0x33, 0x4d, 0x4e, 0x8d, 0x98, 0xb0,
	0x05, 0xed, 0x43, 0x97, 0x68, 0x1e, 0x11, 0xac, 0x4a, 0x8d, 0xc7, 0xcb, 0xe7, 0x18, 0xdf, 0x03,
	0x39, 0x79, 0xd2, 0x89, 0x6b, 0x8c, 0x34, 0x77, 0xf2, 0x11, 0x99, 0x88, 0x05, 0x86, 0x7f, 0x94,
	0x60, 0x2d, 0x8e, 0x76, 0xc4, 0x7f, 0x6c, 0x50, 0x2f, 0xb2, 0xae, 0x09, 0x65, 0xd3, 0x18, 0x19,
	0x1e, 0x93, 0x29, 0xab, 0xc1, 0x02, 0xad, 0xc2, 0x82, 0x3d, 0x18, 0x50, 0xe2, 0x31, 0x7b, 0xcb,
	0x6a, 0xb8, 0xf2, 0xe9, 0x94, 0x68, 0x6e, 0xff, 0x79, 0x68, 0x6e, 0xb8, 0x12, 0x7c, 0x2c, 0x89,
	0x39, 0xff, 0x1e, 0xd6, 0x33, 0x8c, 0x08, 0x13, 0xdf, 0x84, 0x72, 0xdf, 0x1e, 0x5b, 0xb1, 0x15,
	0x6c, 0x91, 0x5a, 0x0e, 0xc5, 0x2b, 0x94, 0x03, 0xee, 0x41, 0xfb, 0xcc, 0xd1, 0x33, 0x33, 0x24,
	0x76, 0xe5, 0x8b, 0xa7, 0xe4, 0x2f, 0x09, 0x5a, 0x7c, 0x0d, 0xb0, 0xa2, 0x0a, 0xb5, 0x47, 0xda,
	0x8a, 0x9c, 0xb6, 0x0f, 0x01, 0xfa, 0xb6, 0x35, 0x30, 0xdc, 0x51, 0xef, 0x7c, 0xc2, 0xce, 0xa9,
	0xef, 0xbd, 0x29, 0xf8, 0x14, 0xec, 0x9f, 0x7a, 0xae, 0xe6, 0x91, 0xa1, 0x41, 0xa8, 0x5a, 0x09,
	0x45, 0x0e, 0x26, 0x68, 0x13, 0x16, 0x29, 0x31, 0x07, 0x3d, 0x97, 0x0c, 0x0d, 0xea, 0x11, 0x97,
	0x59, 0x74, 0x53, 0xad, 0xf9, 0x44, 0x35, 0xa4, 0xa1, 0xdb, 0x50, 0x0b, 0x99, 0xfa, 0xf6, 0x05,
	0x71, 0xe5, 0x32, 0xe3, 0xa9, 0x06, 0x3c, 0x8c, 0x24, 0xe4, 0x6d, 0x41, 0xcc, 0xdb, 0x36, 0x34,
	0xa7, 0xfe, 0xe4, 0x54, 0xd9, 0xbf, 0x12, 0xa0, 0x43, 0x7b, 0xe4, 0x98, 0x84, 0x0f, 0x00, 0x7a,
	0x0f, 0xaa, 0x5c, 0x17, 0x32, 0xfe, 0xbc, 0x26, 0x84, 0x69, 0x13, 0xa2, 0x77, 0xa0, 0xe2, 0x12,
	0x53, 0xf3, 0xd8, 0x14, 0x0b, 0x72, 0xbe, 0x9a, 0x14, 0x54, 0xc3, 0x6d, 0x75, 0xca, 0x88, 0x1e,
	0x42, 0x63, 0x4c, 0x89, 0xdb, 0x33, 0xac, 0x81, 0xdd, 0x1b, 0x18, 0xc4, 0xd4, 0xa3, 0x16, 0x6e,
	0x27, 0x85, 0xcf, 0x28, 0x71, 0xbb, 0xd6, 0xc0, 0x7e, 0xe4, 0xf3, 0xa8, 0xf5, 0x31, 0xbf, 0xa4,
	0x68, 0x07, 0xca, 0xae, 0x6d, 0x12, 0x2a, 0x97, 0x98, 0x2c, 0x12, 0x0e, 0xb6, 0x4d, 0xa2, 0x06,
	0x0c, 0xf8, 0x07, 0x90, 0xe3, 0xc2, 0xf6, 0xed, 0x7e, 0xed, 0x9d, 0x65, 0xc1, 0x1b, 0x29, 0x06,
	0xe4, 0x76, 0xd5, 0xcb, 0xcc, 0x46, 0xfc, 0x87, 0x04, 0x2d, 0xbe, 0x95, 0xf8, 0x42, 0xcf, 0x6a,
	0xa3, 0x6b, 0x58, 0xf8, 0xf8, 0x17, 0x09, 0x1a, 0xfb, 0xba, 0x1e, 0x8e, 0xf2, 0xd0, 0x81, 0x07,
	0x80, 0x84, 0x79, 0x33, 0xbd, 0xc1, 0x1a, 0xc9, 0x99, 0xd2, 0xd5, 0xd1, 0x16, 0xd4, 0xb9, 0x38,
	0x4e, 0x67, 0x7b, 0x6d, 0x1a, 0xaf, 0xae, 0x8e, 0x8e, 0xa0, 0x6e, 0xda, 0x43, 0xc3, 0xea, 0xd1,
	0xc0, 0x9f, 0xc8, 0xe9, 0xf5, 0xa4, 0xd3, 0xc7, 0x3e, 0x0f, 0xe7, 0xf2, 0xa2, 0xc9, 0x11, 0x26,
	0xf8, 0x37, 0x09, 0x96, 0xf9, 0xb0, 0x5f, 0x7f, 0x8b, 0x07, 0xd0, 0x08, 0x87, 0xed, 0x74, 0x6c,
	0xbc, 0x02, 0x6b, 0xf1, 0x77, 0xd0, 0x8c, 0x1b, 0xe0, 0xb5, 0x77, 0xdf, 0xe7, 0xb0, 0x22, 0x1c,
	0x9e, 0xdb, 0x79, 0x1c, 0xb0, 0x28, 0xce, 0x03, 0x2c, 0x7e, 0x96, 0x00, 0xed, 0xeb, 0x7a, 0x3c,
	0xe9, 0x42, 0xd7, 0xe6, 0x4b, 0xe3, 0x2e, 0x94, 0xd8, 0xd4, 0x0d, 0x92, 0xd7, 0x4e, 0x1f, 0x9e,
	0xac, 0xa9, 0x55, 0xc6, 0x18, 0xb7, 0x6b, 0x89, 0x6b, 0xd7, 0x0d, 0xa8, 0xea, 0x84, 0xf6, 0x5d,
	0xc3, 0xf1, 0xb9, 0x59, 0x23, 0x55, 0x54, 0x9e, 0x84, 0x7f, 0x97, 0x60, 0x25, 0xa8, 0x4c, 0xd1,
	0x4c, 0x71, 0x1c, 0x5c, 0x2b, 0xb3, 0xb7, 0x00, 0x45, 0xca, 0x72, 0xee, 0xb5, 0x9f, 0x24, 0x68,
	0xed, 0xeb, 0x7a, 0xf2, 0xb6, 0x78, 0xa1, 0x2c, 0xac, 0x03, 0xb0, 0x7b, 0xa8, 0xc7, 0x01, 0x8a,
	0x0a, 0xa3, 0x7c, 0xe2, 0x1b, 0x1a, 0x6f, 0x33, 0x9f, 0x4b, 0xdc, 0x36, 0xbb, 0x05, 0xdb, 0x50,
	0xd1, 0x35, 0x4f, 0x0b, 0x76, 0x03, 0x2f, 0x6e, 0xfa, 0x04, 0x7f, 0x13, 0xff, 0x2a, 0x81, 0x12,
	0x44, 0x3e, 0xd5, 0xbe, 0xab, 0x85, 0xff, 0x15, 0xda, 0x7b, 0x17, 0x5a, 0x09, 0x43, 0xb3, 0xe3,
	0xbe, 0xf7, 0xf7, 0x12, 0x2c, 0x06, 0xcd, 0x70, 0x1a, 0x64, 0x1e, 0x69, 0xd0, 0x4c, 0xc3, 0xd8,
	0xe8, 0xae, 0xd0, 0x41, 0xd9, 0x38, 0x5c, 0xc9, 0xc5, 0x8c, 0xb8, 0x80, 0x7a, 0x5c, 0x33, 0x47,
	0xe4, 0x83, 0x49, 0xf7, 0x08, 0x6d, 0xe7, 0x09, 0x4e, 0xbd, 0x98, 0x79, 0xc0, 0x37, 0x29, 0x28,
	0xd8, 0x3f, 0x20, 0x7a, 0x25, 0xce, 0x7d, 0xd0, 0x83, 0x3c, 0x3e, 0xf1, 0xcd, 0x89, 0x0b, 0xc8,
	0x4d, 0xf1, 0xcc, 0x1f, 0x57, 0xe8, 0x5e, 0x52, 0x51, 0xde, 0x43, 0x41, 0xb9, 0x3f, 0x17, 0x6f,
	0x7c, 0xa6, 0x06, 0xcd, 0x34, 0xc8, 0x2d, 0x26, 0x2c, 0x07, 0x96, 0xcf, 0x8c, 0xe7, 0x13, 0x68,
	0x1e, 0x91, 0x29, 0xe4, 0x8c, 0x8f, 0x98, 0x37, 0x8c, 0xab, 0x9d, 0xe0, 0x35, 0xdf, 0x89, 0x5e,
	0xf3, 0x9d, 0x87, 0xfe, 0x6b, 0x1e, 0x17, 0xd0, 0x19, 0x34, 0x44, 0x34, 0x8f, 0xee, 0x64, 0x57,
	0x1a, 0x07, 0x82, 0x94, 0x4c, 0x1c, 0x85, 0x0b, 0xe8, 0x19, 0xfc, 0x3f, 0x01, 0xd6, 0x58, 0x75,
	0xe1, 0x2c, 0x01, 0xce, 0xd2, 0x0d, 0x11, 0x21, 0x89, 0x50, 0x1b, 0x17, 0xd0, 0x40, 0x50, 0xce,
	0x12, 0xbc, 0x9d, 0x91, 0x34, 0x01, 0xab, 0x2a, 0x6f, 0xcd, 0xe4, 0x8b, 0x13, 0x7b, 0x06, 0x0d,
	0x11, 0x00, 0x8a, 0xb1, 0xc9, 0x00, 0x88, 0xb9, 0xb1, 0x39, 0x81, 0x06, 0x9f, 0x4c, 0xa6, 0x76,
	0x9e, 0xd0, 0x64, 0x27, 0xf1, 0x10, 0x2a, 0x31, 0xc2, 0x43, 0xb7, 0x92, 0xaa, 0x44, 0xe8, 0xa7,
	0xa4, 0xde, 0xc4, 0xb8, 0x80, 0xba, 0x50, 0xe3, 0xbd, 0x41, 0xb7, 0xb3, 0x3d, 0x9d, 0xa5, 0xea,
	0x11, 0xd4, 0x54, 0x32, 0xb2, 0x2f, 0x48, 0xba, 0x49, 0x22, 0x5a, 0xca, 0xd4, 0xf3, 0x14, 0x16,
	0x13, 0xa0, 0x43, 0x0c, 0x53, 0x1a, 0x1c, 0x52, 0x36, 0x73, 0x79, 0xe2, 0xe4, 0x7e, 0x09, 0x4b,
	0xc2, 0xbf, 0x19, 0xb4, 0x95, 0x21, 0x99, 0xf8, 0xe9, 0xa3, 0xdc, 0x99, 0xc1, 0x15, 0x9f, 0xd0,
	0x85, 0x2a, 0x07, 0x69, 0xd0, 0xc6, 0xa5, 0xbc, 0x08, 0x30, 0x42, 0xc9, 0x78, 0xf6, 0xe1, 0x02,
	0xfa, 0x14, 0xea, 0x49, 0xe4, 0x81, 0x36, 0xd3, 0xb2, 0x33, 0xbf, 0xc2, 0x63, 0xa8, 0x07, 0x19,
	0xca, 0x32, 0xef, 0x32, 0x64, 0xc8, 0xd1, 0xf6, 0x84, 0xbd, 0x30, 0x12, 0x57, 0x9e, 0xd8, 0x28,
	0x19, 0xd8, 0x42, 0xc9, 0x7b, 0xad, 0xe2, 0x02, 0xfa, 0x22, 0x7a, 0x0c, 0x24, 0x95, 0xef, 0xa4,
	0x79, 0x7f, 0x15, 0xfd, 0xcf, 0x60, 0x39, 0x88, 0x43, 0xae, 0xf1, 0x19, 0x97, 0xf9, 0x0c, 0xe5,
	0x07, 0xad, 0xa7, 0x2b, 0x43, 0x62, 0xb1, 0x6e, 0xdd, 0xe5, 0x19, 0xcf, 0x17, 0x18, 0xed, 0xed,
	0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0x1d, 0x46, 0xfd, 0xfd, 0x94, 0x15, 0x00, 0x00,
}
