// Code generated by protoc-gen-go. DO NOT EDIT.
// source: permission_service.proto

package auth_service

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetPermissionByIDResponse struct {
	Id                   string             `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ClientPlatformId     string             `protobuf:"bytes,2,opt,name=client_platform_id,json=clientPlatformId,proto3" json:"client_platform_id,omitempty"`
	ParentId             string             `protobuf:"bytes,3,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Name                 string             `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	PermissionScopes     []*PermissionScope `protobuf:"bytes,5,rep,name=permission_scopes,json=permissionScopes,proto3" json:"permission_scopes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *GetPermissionByIDResponse) Reset()         { *m = GetPermissionByIDResponse{} }
func (m *GetPermissionByIDResponse) String() string { return proto.CompactTextString(m) }
func (*GetPermissionByIDResponse) ProtoMessage()    {}
func (*GetPermissionByIDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef9903376c2df4a6, []int{0}
}

func (m *GetPermissionByIDResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPermissionByIDResponse.Unmarshal(m, b)
}
func (m *GetPermissionByIDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPermissionByIDResponse.Marshal(b, m, deterministic)
}
func (m *GetPermissionByIDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPermissionByIDResponse.Merge(m, src)
}
func (m *GetPermissionByIDResponse) XXX_Size() int {
	return xxx_messageInfo_GetPermissionByIDResponse.Size(m)
}
func (m *GetPermissionByIDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPermissionByIDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPermissionByIDResponse proto.InternalMessageInfo

func (m *GetPermissionByIDResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetPermissionByIDResponse) GetClientPlatformId() string {
	if m != nil {
		return m.ClientPlatformId
	}
	return ""
}

func (m *GetPermissionByIDResponse) GetParentId() string {
	if m != nil {
		return m.ParentId
	}
	return ""
}

func (m *GetPermissionByIDResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetPermissionByIDResponse) GetPermissionScopes() []*PermissionScope {
	if m != nil {
		return m.PermissionScopes
	}
	return nil
}

type GetRoleByIdResponse struct {
	Id                   string        `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ClientTypeId         string        `protobuf:"bytes,2,opt,name=client_type_id,json=clientTypeId,proto3" json:"client_type_id,omitempty"`
	Name                 string        `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	ClientType           *ClientType   `protobuf:"bytes,4,opt,name=client_type,json=clientType,proto3" json:"client_type,omitempty"`
	Permissions          []*Permission `protobuf:"bytes,5,rep,name=permissions,proto3" json:"permissions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetRoleByIdResponse) Reset()         { *m = GetRoleByIdResponse{} }
func (m *GetRoleByIdResponse) String() string { return proto.CompactTextString(m) }
func (*GetRoleByIdResponse) ProtoMessage()    {}
func (*GetRoleByIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef9903376c2df4a6, []int{1}
}

func (m *GetRoleByIdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRoleByIdResponse.Unmarshal(m, b)
}
func (m *GetRoleByIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRoleByIdResponse.Marshal(b, m, deterministic)
}
func (m *GetRoleByIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRoleByIdResponse.Merge(m, src)
}
func (m *GetRoleByIdResponse) XXX_Size() int {
	return xxx_messageInfo_GetRoleByIdResponse.Size(m)
}
func (m *GetRoleByIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRoleByIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetRoleByIdResponse proto.InternalMessageInfo

func (m *GetRoleByIdResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetRoleByIdResponse) GetClientTypeId() string {
	if m != nil {
		return m.ClientTypeId
	}
	return ""
}

func (m *GetRoleByIdResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetRoleByIdResponse) GetClientType() *ClientType {
	if m != nil {
		return m.ClientType
	}
	return nil
}

func (m *GetRoleByIdResponse) GetPermissions() []*Permission {
	if m != nil {
		return m.Permissions
	}
	return nil
}

type UpsertScopeRequest struct {
	ClientPlatformId     string   `protobuf:"bytes,1,opt,name=client_platform_id,json=clientPlatformId,proto3" json:"client_platform_id,omitempty"`
	Path                 string   `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Method               string   `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpsertScopeRequest) Reset()         { *m = UpsertScopeRequest{} }
func (m *UpsertScopeRequest) String() string { return proto.CompactTextString(m) }
func (*UpsertScopeRequest) ProtoMessage()    {}
func (*UpsertScopeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef9903376c2df4a6, []int{2}
}

func (m *UpsertScopeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpsertScopeRequest.Unmarshal(m, b)
}
func (m *UpsertScopeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpsertScopeRequest.Marshal(b, m, deterministic)
}
func (m *UpsertScopeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpsertScopeRequest.Merge(m, src)
}
func (m *UpsertScopeRequest) XXX_Size() int {
	return xxx_messageInfo_UpsertScopeRequest.Size(m)
}
func (m *UpsertScopeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpsertScopeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpsertScopeRequest proto.InternalMessageInfo

func (m *UpsertScopeRequest) GetClientPlatformId() string {
	if m != nil {
		return m.ClientPlatformId
	}
	return ""
}

func (m *UpsertScopeRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *UpsertScopeRequest) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

type ScopePrimaryKey struct {
	ClientPlatformId     string   `protobuf:"bytes,1,opt,name=client_platform_id,json=clientPlatformId,proto3" json:"client_platform_id,omitempty"`
	Path                 string   `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Method               string   `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ScopePrimaryKey) Reset()         { *m = ScopePrimaryKey{} }
func (m *ScopePrimaryKey) String() string { return proto.CompactTextString(m) }
func (*ScopePrimaryKey) ProtoMessage()    {}
func (*ScopePrimaryKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef9903376c2df4a6, []int{3}
}

func (m *ScopePrimaryKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScopePrimaryKey.Unmarshal(m, b)
}
func (m *ScopePrimaryKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScopePrimaryKey.Marshal(b, m, deterministic)
}
func (m *ScopePrimaryKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScopePrimaryKey.Merge(m, src)
}
func (m *ScopePrimaryKey) XXX_Size() int {
	return xxx_messageInfo_ScopePrimaryKey.Size(m)
}
func (m *ScopePrimaryKey) XXX_DiscardUnknown() {
	xxx_messageInfo_ScopePrimaryKey.DiscardUnknown(m)
}

var xxx_messageInfo_ScopePrimaryKey proto.InternalMessageInfo

func (m *ScopePrimaryKey) GetClientPlatformId() string {
	if m != nil {
		return m.ClientPlatformId
	}
	return ""
}

func (m *ScopePrimaryKey) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *ScopePrimaryKey) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

type AddRoleRequest struct {
	ClientTypeId         string   `protobuf:"bytes,2,opt,name=client_type_id,json=clientTypeId,proto3" json:"client_type_id,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	ClientPlatformId     string   `protobuf:"bytes,4,opt,name=client_platform_id,json=clientPlatformId,proto3" json:"client_platform_id,omitempty"`
	ProjectId            string   `protobuf:"bytes,5,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddRoleRequest) Reset()         { *m = AddRoleRequest{} }
func (m *AddRoleRequest) String() string { return proto.CompactTextString(m) }
func (*AddRoleRequest) ProtoMessage()    {}
func (*AddRoleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef9903376c2df4a6, []int{4}
}

func (m *AddRoleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRoleRequest.Unmarshal(m, b)
}
func (m *AddRoleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRoleRequest.Marshal(b, m, deterministic)
}
func (m *AddRoleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRoleRequest.Merge(m, src)
}
func (m *AddRoleRequest) XXX_Size() int {
	return xxx_messageInfo_AddRoleRequest.Size(m)
}
func (m *AddRoleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRoleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddRoleRequest proto.InternalMessageInfo

func (m *AddRoleRequest) GetClientTypeId() string {
	if m != nil {
		return m.ClientTypeId
	}
	return ""
}

func (m *AddRoleRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AddRoleRequest) GetClientPlatformId() string {
	if m != nil {
		return m.ClientPlatformId
	}
	return ""
}

func (m *AddRoleRequest) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

type UpdateRoleRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ClientTypeId         string   `protobuf:"bytes,2,opt,name=client_type_id,json=clientTypeId,proto3" json:"client_type_id,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	ClientPlatformId     string   `protobuf:"bytes,4,opt,name=client_platform_id,json=clientPlatformId,proto3" json:"client_platform_id,omitempty"`
	ProjectId            string   `protobuf:"bytes,5,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRoleRequest) Reset()         { *m = UpdateRoleRequest{} }
func (m *UpdateRoleRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRoleRequest) ProtoMessage()    {}
func (*UpdateRoleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef9903376c2df4a6, []int{5}
}

func (m *UpdateRoleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRoleRequest.Unmarshal(m, b)
}
func (m *UpdateRoleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRoleRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRoleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRoleRequest.Merge(m, src)
}
func (m *UpdateRoleRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRoleRequest.Size(m)
}
func (m *UpdateRoleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRoleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRoleRequest proto.InternalMessageInfo

func (m *UpdateRoleRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateRoleRequest) GetClientTypeId() string {
	if m != nil {
		return m.ClientTypeId
	}
	return ""
}

func (m *UpdateRoleRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateRoleRequest) GetClientPlatformId() string {
	if m != nil {
		return m.ClientPlatformId
	}
	return ""
}

func (m *UpdateRoleRequest) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

type RolePrimaryKey struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RolePrimaryKey) Reset()         { *m = RolePrimaryKey{} }
func (m *RolePrimaryKey) String() string { return proto.CompactTextString(m) }
func (*RolePrimaryKey) ProtoMessage()    {}
func (*RolePrimaryKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef9903376c2df4a6, []int{6}
}

func (m *RolePrimaryKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RolePrimaryKey.Unmarshal(m, b)
}
func (m *RolePrimaryKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RolePrimaryKey.Marshal(b, m, deterministic)
}
func (m *RolePrimaryKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RolePrimaryKey.Merge(m, src)
}
func (m *RolePrimaryKey) XXX_Size() int {
	return xxx_messageInfo_RolePrimaryKey.Size(m)
}
func (m *RolePrimaryKey) XXX_DiscardUnknown() {
	xxx_messageInfo_RolePrimaryKey.DiscardUnknown(m)
}

var xxx_messageInfo_RolePrimaryKey proto.InternalMessageInfo

func (m *RolePrimaryKey) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type CreatePermissionRequest struct {
	ClientPlatformId     string   `protobuf:"bytes,2,opt,name=client_platform_id,json=clientPlatformId,proto3" json:"client_platform_id,omitempty"`
	ParentId             string   `protobuf:"bytes,3,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePermissionRequest) Reset()         { *m = CreatePermissionRequest{} }
func (m *CreatePermissionRequest) String() string { return proto.CompactTextString(m) }
func (*CreatePermissionRequest) ProtoMessage()    {}
func (*CreatePermissionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef9903376c2df4a6, []int{7}
}

func (m *CreatePermissionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePermissionRequest.Unmarshal(m, b)
}
func (m *CreatePermissionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePermissionRequest.Marshal(b, m, deterministic)
}
func (m *CreatePermissionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePermissionRequest.Merge(m, src)
}
func (m *CreatePermissionRequest) XXX_Size() int {
	return xxx_messageInfo_CreatePermissionRequest.Size(m)
}
func (m *CreatePermissionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePermissionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePermissionRequest proto.InternalMessageInfo

func (m *CreatePermissionRequest) GetClientPlatformId() string {
	if m != nil {
		return m.ClientPlatformId
	}
	return ""
}

func (m *CreatePermissionRequest) GetParentId() string {
	if m != nil {
		return m.ParentId
	}
	return ""
}

func (m *CreatePermissionRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type PermissionPrimaryKey struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PermissionPrimaryKey) Reset()         { *m = PermissionPrimaryKey{} }
func (m *PermissionPrimaryKey) String() string { return proto.CompactTextString(m) }
func (*PermissionPrimaryKey) ProtoMessage()    {}
func (*PermissionPrimaryKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef9903376c2df4a6, []int{8}
}

func (m *PermissionPrimaryKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PermissionPrimaryKey.Unmarshal(m, b)
}
func (m *PermissionPrimaryKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PermissionPrimaryKey.Marshal(b, m, deterministic)
}
func (m *PermissionPrimaryKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PermissionPrimaryKey.Merge(m, src)
}
func (m *PermissionPrimaryKey) XXX_Size() int {
	return xxx_messageInfo_PermissionPrimaryKey.Size(m)
}
func (m *PermissionPrimaryKey) XXX_DiscardUnknown() {
	xxx_messageInfo_PermissionPrimaryKey.DiscardUnknown(m)
}

var xxx_messageInfo_PermissionPrimaryKey proto.InternalMessageInfo

func (m *PermissionPrimaryKey) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetPermissionListRequest struct {
	Limit                int32    `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               int32    `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Search               string   `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPermissionListRequest) Reset()         { *m = GetPermissionListRequest{} }
func (m *GetPermissionListRequest) String() string { return proto.CompactTextString(m) }
func (*GetPermissionListRequest) ProtoMessage()    {}
func (*GetPermissionListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef9903376c2df4a6, []int{9}
}

func (m *GetPermissionListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPermissionListRequest.Unmarshal(m, b)
}
func (m *GetPermissionListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPermissionListRequest.Marshal(b, m, deterministic)
}
func (m *GetPermissionListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPermissionListRequest.Merge(m, src)
}
func (m *GetPermissionListRequest) XXX_Size() int {
	return xxx_messageInfo_GetPermissionListRequest.Size(m)
}
func (m *GetPermissionListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPermissionListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPermissionListRequest proto.InternalMessageInfo

func (m *GetPermissionListRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetPermissionListRequest) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *GetPermissionListRequest) GetSearch() string {
	if m != nil {
		return m.Search
	}
	return ""
}

type GetPermissionListResponse struct {
	Count                int32         `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Permissions          []*Permission `protobuf:"bytes,2,rep,name=permissions,proto3" json:"permissions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetPermissionListResponse) Reset()         { *m = GetPermissionListResponse{} }
func (m *GetPermissionListResponse) String() string { return proto.CompactTextString(m) }
func (*GetPermissionListResponse) ProtoMessage()    {}
func (*GetPermissionListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef9903376c2df4a6, []int{10}
}

func (m *GetPermissionListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPermissionListResponse.Unmarshal(m, b)
}
func (m *GetPermissionListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPermissionListResponse.Marshal(b, m, deterministic)
}
func (m *GetPermissionListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPermissionListResponse.Merge(m, src)
}
func (m *GetPermissionListResponse) XXX_Size() int {
	return xxx_messageInfo_GetPermissionListResponse.Size(m)
}
func (m *GetPermissionListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPermissionListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPermissionListResponse proto.InternalMessageInfo

func (m *GetPermissionListResponse) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *GetPermissionListResponse) GetPermissions() []*Permission {
	if m != nil {
		return m.Permissions
	}
	return nil
}

type UpdatePermissionRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ClientPlatformId     string   `protobuf:"bytes,2,opt,name=client_platform_id,json=clientPlatformId,proto3" json:"client_platform_id,omitempty"`
	ParentId             string   `protobuf:"bytes,3,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatePermissionRequest) Reset()         { *m = UpdatePermissionRequest{} }
func (m *UpdatePermissionRequest) String() string { return proto.CompactTextString(m) }
func (*UpdatePermissionRequest) ProtoMessage()    {}
func (*UpdatePermissionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef9903376c2df4a6, []int{11}
}

func (m *UpdatePermissionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePermissionRequest.Unmarshal(m, b)
}
func (m *UpdatePermissionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePermissionRequest.Marshal(b, m, deterministic)
}
func (m *UpdatePermissionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePermissionRequest.Merge(m, src)
}
func (m *UpdatePermissionRequest) XXX_Size() int {
	return xxx_messageInfo_UpdatePermissionRequest.Size(m)
}
func (m *UpdatePermissionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePermissionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePermissionRequest proto.InternalMessageInfo

func (m *UpdatePermissionRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdatePermissionRequest) GetClientPlatformId() string {
	if m != nil {
		return m.ClientPlatformId
	}
	return ""
}

func (m *UpdatePermissionRequest) GetParentId() string {
	if m != nil {
		return m.ParentId
	}
	return ""
}

func (m *UpdatePermissionRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type AddPermissionScopeRequest struct {
	PermissionId         string   `protobuf:"bytes,1,opt,name=permission_id,json=permissionId,proto3" json:"permission_id,omitempty"`
	ClientPlatformId     string   `protobuf:"bytes,2,opt,name=client_platform_id,json=clientPlatformId,proto3" json:"client_platform_id,omitempty"`
	Path                 string   `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Method               string   `protobuf:"bytes,4,opt,name=method,proto3" json:"method,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddPermissionScopeRequest) Reset()         { *m = AddPermissionScopeRequest{} }
func (m *AddPermissionScopeRequest) String() string { return proto.CompactTextString(m) }
func (*AddPermissionScopeRequest) ProtoMessage()    {}
func (*AddPermissionScopeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef9903376c2df4a6, []int{12}
}

func (m *AddPermissionScopeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddPermissionScopeRequest.Unmarshal(m, b)
}
func (m *AddPermissionScopeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddPermissionScopeRequest.Marshal(b, m, deterministic)
}
func (m *AddPermissionScopeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddPermissionScopeRequest.Merge(m, src)
}
func (m *AddPermissionScopeRequest) XXX_Size() int {
	return xxx_messageInfo_AddPermissionScopeRequest.Size(m)
}
func (m *AddPermissionScopeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddPermissionScopeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddPermissionScopeRequest proto.InternalMessageInfo

func (m *AddPermissionScopeRequest) GetPermissionId() string {
	if m != nil {
		return m.PermissionId
	}
	return ""
}

func (m *AddPermissionScopeRequest) GetClientPlatformId() string {
	if m != nil {
		return m.ClientPlatformId
	}
	return ""
}

func (m *AddPermissionScopeRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *AddPermissionScopeRequest) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

type PermissionScopePrimaryKey struct {
	PermissionId         string   `protobuf:"bytes,1,opt,name=permission_id,json=permissionId,proto3" json:"permission_id,omitempty"`
	ClientPlatformId     string   `protobuf:"bytes,2,opt,name=client_platform_id,json=clientPlatformId,proto3" json:"client_platform_id,omitempty"`
	Path                 string   `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Method               string   `protobuf:"bytes,4,opt,name=method,proto3" json:"method,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PermissionScopePrimaryKey) Reset()         { *m = PermissionScopePrimaryKey{} }
func (m *PermissionScopePrimaryKey) String() string { return proto.CompactTextString(m) }
func (*PermissionScopePrimaryKey) ProtoMessage()    {}
func (*PermissionScopePrimaryKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef9903376c2df4a6, []int{13}
}

func (m *PermissionScopePrimaryKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PermissionScopePrimaryKey.Unmarshal(m, b)
}
func (m *PermissionScopePrimaryKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PermissionScopePrimaryKey.Marshal(b, m, deterministic)
}
func (m *PermissionScopePrimaryKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PermissionScopePrimaryKey.Merge(m, src)
}
func (m *PermissionScopePrimaryKey) XXX_Size() int {
	return xxx_messageInfo_PermissionScopePrimaryKey.Size(m)
}
func (m *PermissionScopePrimaryKey) XXX_DiscardUnknown() {
	xxx_messageInfo_PermissionScopePrimaryKey.DiscardUnknown(m)
}

var xxx_messageInfo_PermissionScopePrimaryKey proto.InternalMessageInfo

func (m *PermissionScopePrimaryKey) GetPermissionId() string {
	if m != nil {
		return m.PermissionId
	}
	return ""
}

func (m *PermissionScopePrimaryKey) GetClientPlatformId() string {
	if m != nil {
		return m.ClientPlatformId
	}
	return ""
}

func (m *PermissionScopePrimaryKey) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *PermissionScopePrimaryKey) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

type AddRolePermissionRequest struct {
	RoleId               string   `protobuf:"bytes,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	PermissionId         string   `protobuf:"bytes,2,opt,name=permission_id,json=permissionId,proto3" json:"permission_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddRolePermissionRequest) Reset()         { *m = AddRolePermissionRequest{} }
func (m *AddRolePermissionRequest) String() string { return proto.CompactTextString(m) }
func (*AddRolePermissionRequest) ProtoMessage()    {}
func (*AddRolePermissionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef9903376c2df4a6, []int{14}
}

func (m *AddRolePermissionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRolePermissionRequest.Unmarshal(m, b)
}
func (m *AddRolePermissionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRolePermissionRequest.Marshal(b, m, deterministic)
}
func (m *AddRolePermissionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRolePermissionRequest.Merge(m, src)
}
func (m *AddRolePermissionRequest) XXX_Size() int {
	return xxx_messageInfo_AddRolePermissionRequest.Size(m)
}
func (m *AddRolePermissionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRolePermissionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddRolePermissionRequest proto.InternalMessageInfo

func (m *AddRolePermissionRequest) GetRoleId() string {
	if m != nil {
		return m.RoleId
	}
	return ""
}

func (m *AddRolePermissionRequest) GetPermissionId() string {
	if m != nil {
		return m.PermissionId
	}
	return ""
}

type AddRolePermissionsRequest struct {
	Permissions          []*AddRolePermissionRequest `protobuf:"bytes,1,rep,name=permissions,proto3" json:"permissions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *AddRolePermissionsRequest) Reset()         { *m = AddRolePermissionsRequest{} }
func (m *AddRolePermissionsRequest) String() string { return proto.CompactTextString(m) }
func (*AddRolePermissionsRequest) ProtoMessage()    {}
func (*AddRolePermissionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef9903376c2df4a6, []int{15}
}

func (m *AddRolePermissionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRolePermissionsRequest.Unmarshal(m, b)
}
func (m *AddRolePermissionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRolePermissionsRequest.Marshal(b, m, deterministic)
}
func (m *AddRolePermissionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRolePermissionsRequest.Merge(m, src)
}
func (m *AddRolePermissionsRequest) XXX_Size() int {
	return xxx_messageInfo_AddRolePermissionsRequest.Size(m)
}
func (m *AddRolePermissionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRolePermissionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddRolePermissionsRequest proto.InternalMessageInfo

func (m *AddRolePermissionsRequest) GetPermissions() []*AddRolePermissionRequest {
	if m != nil {
		return m.Permissions
	}
	return nil
}

type AddRolePermissionsResponse struct {
	AddedRoles           int64    `protobuf:"varint,1,opt,name=added_roles,json=addedRoles,proto3" json:"added_roles,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddRolePermissionsResponse) Reset()         { *m = AddRolePermissionsResponse{} }
func (m *AddRolePermissionsResponse) String() string { return proto.CompactTextString(m) }
func (*AddRolePermissionsResponse) ProtoMessage()    {}
func (*AddRolePermissionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef9903376c2df4a6, []int{16}
}

func (m *AddRolePermissionsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRolePermissionsResponse.Unmarshal(m, b)
}
func (m *AddRolePermissionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRolePermissionsResponse.Marshal(b, m, deterministic)
}
func (m *AddRolePermissionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRolePermissionsResponse.Merge(m, src)
}
func (m *AddRolePermissionsResponse) XXX_Size() int {
	return xxx_messageInfo_AddRolePermissionsResponse.Size(m)
}
func (m *AddRolePermissionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRolePermissionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddRolePermissionsResponse proto.InternalMessageInfo

func (m *AddRolePermissionsResponse) GetAddedRoles() int64 {
	if m != nil {
		return m.AddedRoles
	}
	return 0
}

type RolePermissionPrimaryKey struct {
	RoleId               string   `protobuf:"bytes,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	PermissionId         string   `protobuf:"bytes,2,opt,name=permission_id,json=permissionId,proto3" json:"permission_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RolePermissionPrimaryKey) Reset()         { *m = RolePermissionPrimaryKey{} }
func (m *RolePermissionPrimaryKey) String() string { return proto.CompactTextString(m) }
func (*RolePermissionPrimaryKey) ProtoMessage()    {}
func (*RolePermissionPrimaryKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef9903376c2df4a6, []int{17}
}

func (m *RolePermissionPrimaryKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RolePermissionPrimaryKey.Unmarshal(m, b)
}
func (m *RolePermissionPrimaryKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RolePermissionPrimaryKey.Marshal(b, m, deterministic)
}
func (m *RolePermissionPrimaryKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RolePermissionPrimaryKey.Merge(m, src)
}
func (m *RolePermissionPrimaryKey) XXX_Size() int {
	return xxx_messageInfo_RolePermissionPrimaryKey.Size(m)
}
func (m *RolePermissionPrimaryKey) XXX_DiscardUnknown() {
	xxx_messageInfo_RolePermissionPrimaryKey.DiscardUnknown(m)
}

var xxx_messageInfo_RolePermissionPrimaryKey proto.InternalMessageInfo

func (m *RolePermissionPrimaryKey) GetRoleId() string {
	if m != nil {
		return m.RoleId
	}
	return ""
}

func (m *RolePermissionPrimaryKey) GetPermissionId() string {
	if m != nil {
		return m.PermissionId
	}
	return ""
}

type GetRolesListRequest struct {
	Offset               uint32   `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit                uint32   `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	ClientPlatformId     string   `protobuf:"bytes,3,opt,name=client_platform_id,json=clientPlatformId,proto3" json:"client_platform_id,omitempty"`
	ClientTypeId         string   `protobuf:"bytes,4,opt,name=client_type_id,json=clientTypeId,proto3" json:"client_type_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRolesListRequest) Reset()         { *m = GetRolesListRequest{} }
func (m *GetRolesListRequest) String() string { return proto.CompactTextString(m) }
func (*GetRolesListRequest) ProtoMessage()    {}
func (*GetRolesListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef9903376c2df4a6, []int{18}
}

func (m *GetRolesListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRolesListRequest.Unmarshal(m, b)
}
func (m *GetRolesListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRolesListRequest.Marshal(b, m, deterministic)
}
func (m *GetRolesListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRolesListRequest.Merge(m, src)
}
func (m *GetRolesListRequest) XXX_Size() int {
	return xxx_messageInfo_GetRolesListRequest.Size(m)
}
func (m *GetRolesListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRolesListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRolesListRequest proto.InternalMessageInfo

func (m *GetRolesListRequest) GetOffset() uint32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *GetRolesListRequest) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetRolesListRequest) GetClientPlatformId() string {
	if m != nil {
		return m.ClientPlatformId
	}
	return ""
}

func (m *GetRolesListRequest) GetClientTypeId() string {
	if m != nil {
		return m.ClientTypeId
	}
	return ""
}

type GetRolesResponse struct {
	Roles                []*Role  `protobuf:"bytes,1,rep,name=roles,proto3" json:"roles,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRolesResponse) Reset()         { *m = GetRolesResponse{} }
func (m *GetRolesResponse) String() string { return proto.CompactTextString(m) }
func (*GetRolesResponse) ProtoMessage()    {}
func (*GetRolesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef9903376c2df4a6, []int{19}
}

func (m *GetRolesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRolesResponse.Unmarshal(m, b)
}
func (m *GetRolesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRolesResponse.Marshal(b, m, deterministic)
}
func (m *GetRolesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRolesResponse.Merge(m, src)
}
func (m *GetRolesResponse) XXX_Size() int {
	return xxx_messageInfo_GetRolesResponse.Size(m)
}
func (m *GetRolesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRolesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetRolesResponse proto.InternalMessageInfo

func (m *GetRolesResponse) GetRoles() []*Role {
	if m != nil {
		return m.Roles
	}
	return nil
}

func init() {
	proto.RegisterType((*GetPermissionByIDResponse)(nil), "auth_service.GetPermissionByIDResponse")
	proto.RegisterType((*GetRoleByIdResponse)(nil), "auth_service.GetRoleByIdResponse")
	proto.RegisterType((*UpsertScopeRequest)(nil), "auth_service.UpsertScopeRequest")
	proto.RegisterType((*ScopePrimaryKey)(nil), "auth_service.ScopePrimaryKey")
	proto.RegisterType((*AddRoleRequest)(nil), "auth_service.AddRoleRequest")
	proto.RegisterType((*UpdateRoleRequest)(nil), "auth_service.UpdateRoleRequest")
	proto.RegisterType((*RolePrimaryKey)(nil), "auth_service.RolePrimaryKey")
	proto.RegisterType((*CreatePermissionRequest)(nil), "auth_service.CreatePermissionRequest")
	proto.RegisterType((*PermissionPrimaryKey)(nil), "auth_service.PermissionPrimaryKey")
	proto.RegisterType((*GetPermissionListRequest)(nil), "auth_service.GetPermissionListRequest")
	proto.RegisterType((*GetPermissionListResponse)(nil), "auth_service.GetPermissionListResponse")
	proto.RegisterType((*UpdatePermissionRequest)(nil), "auth_service.UpdatePermissionRequest")
	proto.RegisterType((*AddPermissionScopeRequest)(nil), "auth_service.AddPermissionScopeRequest")
	proto.RegisterType((*PermissionScopePrimaryKey)(nil), "auth_service.PermissionScopePrimaryKey")
	proto.RegisterType((*AddRolePermissionRequest)(nil), "auth_service.AddRolePermissionRequest")
	proto.RegisterType((*AddRolePermissionsRequest)(nil), "auth_service.AddRolePermissionsRequest")
	proto.RegisterType((*AddRolePermissionsResponse)(nil), "auth_service.AddRolePermissionsResponse")
	proto.RegisterType((*RolePermissionPrimaryKey)(nil), "auth_service.RolePermissionPrimaryKey")
	proto.RegisterType((*GetRolesListRequest)(nil), "auth_service.GetRolesListRequest")
	proto.RegisterType((*GetRolesResponse)(nil), "auth_service.GetRolesResponse")
}

func init() { proto.RegisterFile("permission_service.proto", fileDescriptor_ef9903376c2df4a6) }

var fileDescriptor_ef9903376c2df4a6 = []byte{
	// 994 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x57, 0xef, 0x6e, 0xdc, 0x44,
	0x10, 0x3f, 0xdf, 0x9f, 0x94, 0xcc, 0xa5, 0xe1, 0x6e, 0x9b, 0x36, 0xae, 0x4b, 0x69, 0x58, 0x20,
	0xc9, 0x07, 0x74, 0x91, 0xc2, 0x27, 0x10, 0x95, 0x68, 0x52, 0x28, 0x07, 0x7c, 0x38, 0xb9, 0x54,
	0x42, 0x20, 0x35, 0x38, 0xb7, 0x73, 0x89, 0xe1, 0x7c, 0x36, 0xde, 0x4d, 0xc5, 0xbd, 0x01, 0x6f,
	0x50, 0x09, 0x89, 0x17, 0xe0, 0x81, 0x78, 0x1e, 0xb4, 0xeb, 0x7f, 0x6b, 0x7b, 0x9d, 0x4b, 0x20,
	0xc0, 0x37, 0xef, 0xec, 0xec, 0xce, 0x6f, 0x66, 0x7e, 0x33, 0xb3, 0x06, 0x3b, 0xc2, 0x38, 0xf0,
	0x39, 0xf7, 0xc3, 0xc5, 0x09, 0xc7, 0xf8, 0x95, 0x3f, 0xc5, 0x51, 0x14, 0x87, 0x22, 0x24, 0x1b,
	0xde, 0x85, 0x38, 0xcf, 0x64, 0x0e, 0xc8, 0x55, 0xb2, 0xe3, 0x3c, 0x38, 0x0b, 0xc3, 0xb3, 0x39,
	0x1e, 0xa8, 0xd5, 0xe9, 0xc5, 0xec, 0x00, 0x83, 0x48, 0x2c, 0x93, 0x4d, 0xfa, 0xa7, 0x05, 0xf7,
	0x9f, 0xa1, 0x98, 0xe4, 0xd7, 0x1e, 0x2d, 0xc7, 0x4f, 0x5d, 0xe4, 0x51, 0xb8, 0xe0, 0x48, 0x36,
	0xa1, 0xed, 0x33, 0xdb, 0xda, 0xb1, 0xf6, 0xd7, 0xdd, 0xb6, 0xcf, 0xc8, 0x07, 0x40, 0xa6, 0x73,
	0x1f, 0x17, 0xe2, 0x24, 0x9a, 0x7b, 0x62, 0x16, 0xc6, 0xc1, 0x89, 0xcf, 0xec, 0xb6, 0xda, 0x1f,
	0x24, 0x3b, 0x93, 0x74, 0x63, 0xcc, 0xc8, 0x03, 0x58, 0x8f, 0xbc, 0x58, 0x6a, 0xfb, 0xcc, 0xee,
	0x28, 0xa5, 0x37, 0x12, 0xc1, 0x98, 0x11, 0x02, 0xdd, 0x85, 0x17, 0xa0, 0xdd, 0x55, 0x72, 0xf5,
	0x4d, 0xbe, 0x84, 0xa1, 0xee, 0xdf, 0x34, 0x8c, 0x90, 0xdb, 0xbd, 0x9d, 0xce, 0x7e, 0xff, 0xf0,
	0xe1, 0x48, 0xf7, 0x6f, 0x54, 0xe0, 0x7d, 0x2e, 0xb5, 0xdc, 0x41, 0x54, 0x16, 0x70, 0xe9, 0xd8,
	0x9d, 0x67, 0x28, 0xdc, 0x70, 0x8e, 0x47, 0xcb, 0x31, 0x6b, 0x74, 0xe9, 0x3d, 0xd8, 0x4c, 0x5d,
	0x12, 0xcb, 0x08, 0x0b, 0x77, 0x36, 0x12, 0xe9, 0x37, 0xcb, 0x08, 0x35, 0xb4, 0x1d, 0x0d, 0xed,
	0x47, 0xd0, 0xd7, 0x4e, 0x2a, 0x47, 0xfa, 0x87, 0x76, 0x19, 0xe7, 0x71, 0x7e, 0x89, 0x0b, 0xc5,
	0x85, 0xe4, 0x63, 0xe8, 0x17, 0x80, 0x33, 0x17, 0xed, 0x26, 0x17, 0x5d, 0x5d, 0x99, 0x2e, 0x80,
	0xbc, 0x88, 0x38, 0xc6, 0x22, 0xf1, 0x1c, 0x7f, 0xbe, 0x40, 0x2e, 0x1a, 0x32, 0x63, 0x35, 0x64,
	0x86, 0x40, 0x37, 0xf2, 0xc4, 0x79, 0xea, 0xaa, 0xfa, 0x26, 0xf7, 0x60, 0x2d, 0x40, 0x71, 0x1e,
	0x66, 0xa9, 0x4a, 0x57, 0xf4, 0x27, 0x78, 0x53, 0x59, 0x9a, 0xc4, 0x7e, 0xe0, 0xc5, 0xcb, 0xaf,
	0x70, 0xf9, 0x2f, 0x1a, 0x7b, 0x6d, 0xc1, 0xe6, 0x13, 0xc6, 0x64, 0xd6, 0x32, 0xcf, 0xfe, 0x7e,
	0x82, 0xcc, 0x30, 0xbb, 0x0d, 0x30, 0x1f, 0x02, 0x44, 0x71, 0xf8, 0x23, 0x4e, 0x15, 0x5d, 0x7b,
	0x4a, 0x6b, 0x3d, 0x95, 0x8c, 0x19, 0xfd, 0xc3, 0x82, 0xe1, 0x8b, 0x88, 0x79, 0x02, 0x75, 0x70,
	0x37, 0xc7, 0xa6, 0x1b, 0x05, 0xbb, 0x03, 0x9b, 0x12, 0xa5, 0x96, 0xb2, 0x0a, 0x50, 0xfa, 0x0b,
	0x6c, 0x1f, 0xc7, 0xe8, 0x09, 0xd4, 0x68, 0x76, 0x29, 0x95, 0x6e, 0xaa, 0xc8, 0xe9, 0x2e, 0x6c,
	0x15, 0x36, 0x2f, 0x41, 0xf8, 0x03, 0xd8, 0xa5, 0xc6, 0xf4, 0xb5, 0xcf, 0x45, 0x06, 0x71, 0x0b,
	0x7a, 0x73, 0x3f, 0xf0, 0x85, 0x52, 0xef, 0xb9, 0xc9, 0x42, 0x92, 0x2a, 0x9c, 0xcd, 0x38, 0x0a,
	0x05, 0xb6, 0xe7, 0xa6, 0x2b, 0x29, 0xe7, 0xe8, 0xc5, 0xd3, 0xf3, 0x8c, 0x6c, 0xc9, 0x8a, 0x06,
	0x95, 0xd6, 0x97, 0x58, 0x48, 0xfb, 0xc4, 0x16, 0xf4, 0xa6, 0xe1, 0xc5, 0x22, 0x37, 0xa1, 0x16,
	0xd5, 0xc2, 0x6d, 0x5f, 0xa7, 0x70, 0x7f, 0xb5, 0x60, 0x3b, 0x61, 0x50, 0x3d, 0xe6, 0xff, 0x6d,
	0xa3, 0xa5, 0xbf, 0x59, 0x70, 0xff, 0x09, 0x63, 0xd5, 0x2e, 0x9a, 0x82, 0x79, 0x17, 0x6e, 0x6b,
	0x6d, 0x38, 0xc7, 0xb5, 0x51, 0x08, 0xc7, 0xd7, 0x45, 0x98, 0xf5, 0x80, 0x8e, 0xb1, 0x07, 0x74,
	0x4b, 0x3d, 0x40, 0x82, 0xab, 0x20, 0xd3, 0x68, 0xf2, 0x3f, 0x83, 0xfb, 0x16, 0xec, 0xb4, 0x3f,
	0xd5, 0x93, 0xb8, 0x0d, 0xb7, 0xe2, 0x70, 0x8e, 0x05, 0xa8, 0x35, 0xb9, 0x1c, 0xb3, 0x3a, 0xe6,
	0x76, 0x1d, 0x33, 0x45, 0x95, 0x92, 0xf2, 0xcd, 0x3c, 0xbb, 0xfa, 0x8b, 0x32, 0xef, 0x2c, 0xc5,
	0xbb, 0xdd, 0x32, 0xef, 0x9a, 0x70, 0x95, 0x59, 0xf8, 0x18, 0x1c, 0x93, 0x99, 0x94, 0xf5, 0x8f,
	0xa0, 0xef, 0x31, 0x86, 0xec, 0x44, 0x22, 0xe7, 0xca, 0x8d, 0x8e, 0x0b, 0x4a, 0x24, 0x8f, 0x70,
	0xe9, 0x7f, 0xf9, 0xac, 0x96, 0x9a, 0x7f, 0xe6, 0xff, 0xeb, 0x62, 0x60, 0x73, 0xbd, 0xd6, 0x8b,
	0xaa, 0x96, 0x97, 0xde, 0xce, 0xab, 0x3a, 0xef, 0x01, 0x6d, 0x25, 0x4e, 0x7b, 0x80, 0x39, 0xf3,
	0x9d, 0x86, 0xcc, 0xd7, 0xdb, 0x75, 0xb7, 0xde, 0xae, 0xe9, 0x27, 0x30, 0xc8, 0x80, 0xe5, 0x81,
	0xda, 0x87, 0x5e, 0x16, 0x22, 0x99, 0x0a, 0x52, 0x4e, 0x85, 0x1a, 0x11, 0x89, 0xc2, 0xe1, 0xef,
	0x7d, 0x18, 0x6a, 0x74, 0x4e, 0x34, 0xc8, 0x04, 0xfa, 0xda, 0xeb, 0x84, 0xbc, 0x55, 0x3f, 0x5f,
	0x04, 0xd6, 0x79, 0xa7, 0xbc, 0x6b, 0x78, 0xd6, 0xd0, 0x16, 0x79, 0x0e, 0x1b, 0x7a, 0xf8, 0x88,
	0xf9, 0x90, 0x1e, 0x5a, 0xe7, 0x6d, 0xb3, 0x8a, 0x76, 0xe9, 0x63, 0xb8, 0x95, 0xb2, 0xa5, 0x0a,
	0xb1, 0x3c, 0xa5, 0x1d, 0x43, 0x00, 0x68, 0x8b, 0x1c, 0x03, 0x14, 0x33, 0x93, 0x3c, 0x2a, 0xeb,
	0xd4, 0xa6, 0x69, 0xc3, 0x25, 0x9f, 0x02, 0xb8, 0x18, 0x84, 0xaf, 0xd0, 0x04, 0xa3, 0x12, 0x29,
	0xf3, 0x0d, 0x0c, 0x06, 0xd5, 0x61, 0x47, 0xde, 0xaf, 0x3c, 0xd4, 0xcc, 0xc3, 0xd0, 0xd9, 0xab,
	0x85, 0xc8, 0xfc, 0x54, 0xa6, 0x2d, 0x72, 0x0a, 0xc3, 0xda, 0x36, 0xa1, 0x4d, 0xb3, 0x41, 0x03,
	0x7d, 0x0d, 0x1b, 0xb3, 0x8a, 0x0d, 0x95, 0xe9, 0xdd, 0x4b, 0xce, 0xeb, 0xe9, 0xde, 0x5b, 0xa9,
	0x97, 0xdb, 0x61, 0x30, 0xa8, 0x8e, 0xaa, 0x6a, 0xc4, 0x1a, 0x46, 0xd9, 0x75, 0xbc, 0x99, 0xc0,
	0xe0, 0x29, 0xce, 0xb1, 0x64, 0xe5, 0x2a, 0x01, 0xbb, 0x37, 0x4a, 0x7e, 0x69, 0x46, 0xd9, 0x2f,
	0xcd, 0xe8, 0x33, 0xf9, 0x4b, 0x43, 0x5b, 0xe4, 0x73, 0xe8, 0x6b, 0x8f, 0x63, 0xb2, 0x53, 0x85,
	0x5c, 0x7d, 0x37, 0x3b, 0x77, 0xca, 0x1a, 0x6a, 0x8f, 0xb6, 0xc8, 0x4b, 0x20, 0xf5, 0xf9, 0x48,
	0xf6, 0x6a, 0x25, 0x60, 0x9e, 0xa0, 0xce, 0xe5, 0x7f, 0x2b, 0xb4, 0x45, 0x3c, 0xb8, 0x9b, 0x70,
	0x7a, 0x85, 0x89, 0xc6, 0x39, 0xb8, 0xda, 0xc4, 0xf7, 0x30, 0xac, 0x35, 0x7a, 0x72, 0xc5, 0x91,
	0xe1, 0x98, 0xaa, 0x2c, 0x57, 0xa2, 0x2d, 0xe2, 0xab, 0xf8, 0x54, 0xa6, 0x88, 0x21, 0x3e, 0xe6,
	0x71, 0xe6, 0xec, 0xaf, 0x56, 0xcc, 0x49, 0xf2, 0x12, 0xb6, 0x8a, 0xf2, 0x6f, 0x76, 0xa5, 0x69,
	0x2a, 0xad, 0x72, 0xe5, 0x68, 0xfb, 0xbb, 0xbb, 0x67, 0xb8, 0x50, 0x4c, 0x3a, 0xd0, 0x35, 0x4f,
	0xd7, 0x94, 0xec, 0xc3, 0xbf, 0x02, 0x00, 0x00, 0xff, 0xff, 0x15, 0xf0, 0xf1, 0x9d, 0x74, 0x0f,
	0x00, 0x00,
}
