// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user_service.proto

package auth_service

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	_struct "github.com/golang/protobuf/ptypes/struct"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UpsertUserInfoRequest struct {
	UserId               string          `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Data                 *_struct.Struct `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *UpsertUserInfoRequest) Reset()         { *m = UpsertUserInfoRequest{} }
func (m *UpsertUserInfoRequest) String() string { return proto.CompactTextString(m) }
func (*UpsertUserInfoRequest) ProtoMessage()    {}
func (*UpsertUserInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_292f630cd9eb4c90, []int{0}
}

func (m *UpsertUserInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpsertUserInfoRequest.Unmarshal(m, b)
}
func (m *UpsertUserInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpsertUserInfoRequest.Marshal(b, m, deterministic)
}
func (m *UpsertUserInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpsertUserInfoRequest.Merge(m, src)
}
func (m *UpsertUserInfoRequest) XXX_Size() int {
	return xxx_messageInfo_UpsertUserInfoRequest.Size(m)
}
func (m *UpsertUserInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpsertUserInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpsertUserInfoRequest proto.InternalMessageInfo

func (m *UpsertUserInfoRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UpsertUserInfoRequest) GetData() *_struct.Struct {
	if m != nil {
		return m.Data
	}
	return nil
}

type CreateUserRequest struct {
	ProjectId            string   `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	ClientPlatformId     string   `protobuf:"bytes,3,opt,name=client_platform_id,json=clientPlatformId,proto3" json:"client_platform_id,omitempty"`
	ClientTypeId         string   `protobuf:"bytes,4,opt,name=client_type_id,json=clientTypeId,proto3" json:"client_type_id,omitempty"`
	RoleId               string   `protobuf:"bytes,5,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	Phone                string   `protobuf:"bytes,6,opt,name=phone,proto3" json:"phone,omitempty"`
	Email                string   `protobuf:"bytes,7,opt,name=email,proto3" json:"email,omitempty"`
	Login                string   `protobuf:"bytes,8,opt,name=login,proto3" json:"login,omitempty"`
	Password             string   `protobuf:"bytes,9,opt,name=password,proto3" json:"password,omitempty"`
	Active               int32    `protobuf:"varint,10,opt,name=active,proto3" json:"active,omitempty"`
	ExpiresAt            string   `protobuf:"bytes,11,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Name                 string   `protobuf:"bytes,14,opt,name=name,proto3" json:"name,omitempty"`
	PhotoUrl             string   `protobuf:"bytes,15,opt,name=photo_url,json=photoUrl,proto3" json:"photo_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_292f630cd9eb4c90, []int{1}
}

func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(m, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

func (m *CreateUserRequest) GetClientPlatformId() string {
	if m != nil {
		return m.ClientPlatformId
	}
	return ""
}

func (m *CreateUserRequest) GetClientTypeId() string {
	if m != nil {
		return m.ClientTypeId
	}
	return ""
}

func (m *CreateUserRequest) GetRoleId() string {
	if m != nil {
		return m.RoleId
	}
	return ""
}

func (m *CreateUserRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *CreateUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateUserRequest) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *CreateUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *CreateUserRequest) GetActive() int32 {
	if m != nil {
		return m.Active
	}
	return 0
}

func (m *CreateUserRequest) GetExpiresAt() string {
	if m != nil {
		return m.ExpiresAt
	}
	return ""
}

func (m *CreateUserRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateUserRequest) GetPhotoUrl() string {
	if m != nil {
		return m.PhotoUrl
	}
	return ""
}

type UserPrimaryKey struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserPrimaryKey) Reset()         { *m = UserPrimaryKey{} }
func (m *UserPrimaryKey) String() string { return proto.CompactTextString(m) }
func (*UserPrimaryKey) ProtoMessage()    {}
func (*UserPrimaryKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_292f630cd9eb4c90, []int{2}
}

func (m *UserPrimaryKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserPrimaryKey.Unmarshal(m, b)
}
func (m *UserPrimaryKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserPrimaryKey.Marshal(b, m, deterministic)
}
func (m *UserPrimaryKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserPrimaryKey.Merge(m, src)
}
func (m *UserPrimaryKey) XXX_Size() int {
	return xxx_messageInfo_UserPrimaryKey.Size(m)
}
func (m *UserPrimaryKey) XXX_DiscardUnknown() {
	xxx_messageInfo_UserPrimaryKey.DiscardUnknown(m)
}

var xxx_messageInfo_UserPrimaryKey proto.InternalMessageInfo

func (m *UserPrimaryKey) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type UserPrimaryKeyList struct {
	Ids                  []string `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserPrimaryKeyList) Reset()         { *m = UserPrimaryKeyList{} }
func (m *UserPrimaryKeyList) String() string { return proto.CompactTextString(m) }
func (*UserPrimaryKeyList) ProtoMessage()    {}
func (*UserPrimaryKeyList) Descriptor() ([]byte, []int) {
	return fileDescriptor_292f630cd9eb4c90, []int{3}
}

func (m *UserPrimaryKeyList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserPrimaryKeyList.Unmarshal(m, b)
}
func (m *UserPrimaryKeyList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserPrimaryKeyList.Marshal(b, m, deterministic)
}
func (m *UserPrimaryKeyList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserPrimaryKeyList.Merge(m, src)
}
func (m *UserPrimaryKeyList) XXX_Size() int {
	return xxx_messageInfo_UserPrimaryKeyList.Size(m)
}
func (m *UserPrimaryKeyList) XXX_DiscardUnknown() {
	xxx_messageInfo_UserPrimaryKeyList.DiscardUnknown(m)
}

var xxx_messageInfo_UserPrimaryKeyList proto.InternalMessageInfo

func (m *UserPrimaryKeyList) GetIds() []string {
	if m != nil {
		return m.Ids
	}
	return nil
}

type GetUserListRequest struct {
	Limit                int32    `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               int32    `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Search               string   `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	ClientPlatformId     string   `protobuf:"bytes,4,opt,name=client_platform_id,json=clientPlatformId,proto3" json:"client_platform_id,omitempty"`
	ClientTypeId         string   `protobuf:"bytes,5,opt,name=client_type_id,json=clientTypeId,proto3" json:"client_type_id,omitempty"`
	ProjectId            string   `protobuf:"bytes,6,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserListRequest) Reset()         { *m = GetUserListRequest{} }
func (m *GetUserListRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserListRequest) ProtoMessage()    {}
func (*GetUserListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_292f630cd9eb4c90, []int{4}
}

func (m *GetUserListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserListRequest.Unmarshal(m, b)
}
func (m *GetUserListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserListRequest.Marshal(b, m, deterministic)
}
func (m *GetUserListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserListRequest.Merge(m, src)
}
func (m *GetUserListRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserListRequest.Size(m)
}
func (m *GetUserListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserListRequest proto.InternalMessageInfo

func (m *GetUserListRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetUserListRequest) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *GetUserListRequest) GetSearch() string {
	if m != nil {
		return m.Search
	}
	return ""
}

func (m *GetUserListRequest) GetClientPlatformId() string {
	if m != nil {
		return m.ClientPlatformId
	}
	return ""
}

func (m *GetUserListRequest) GetClientTypeId() string {
	if m != nil {
		return m.ClientTypeId
	}
	return ""
}

func (m *GetUserListRequest) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

type GetUserListResponse struct {
	Count                int32    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Users                []*User  `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserListResponse) Reset()         { *m = GetUserListResponse{} }
func (m *GetUserListResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserListResponse) ProtoMessage()    {}
func (*GetUserListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_292f630cd9eb4c90, []int{5}
}

func (m *GetUserListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserListResponse.Unmarshal(m, b)
}
func (m *GetUserListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserListResponse.Marshal(b, m, deterministic)
}
func (m *GetUserListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserListResponse.Merge(m, src)
}
func (m *GetUserListResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserListResponse.Size(m)
}
func (m *GetUserListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserListResponse proto.InternalMessageInfo

func (m *GetUserListResponse) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *GetUserListResponse) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

type UpdateUserRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProjectId            string   `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	ClientPlatformId     string   `protobuf:"bytes,3,opt,name=client_platform_id,json=clientPlatformId,proto3" json:"client_platform_id,omitempty"`
	ClientTypeId         string   `protobuf:"bytes,4,opt,name=client_type_id,json=clientTypeId,proto3" json:"client_type_id,omitempty"`
	RoleId               string   `protobuf:"bytes,5,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	Phone                string   `protobuf:"bytes,6,opt,name=phone,proto3" json:"phone,omitempty"`
	Email                string   `protobuf:"bytes,7,opt,name=email,proto3" json:"email,omitempty"`
	Login                string   `protobuf:"bytes,8,opt,name=login,proto3" json:"login,omitempty"`
	Active               int32    `protobuf:"varint,10,opt,name=active,proto3" json:"active,omitempty"`
	ExpiresAt            string   `protobuf:"bytes,11,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Name                 string   `protobuf:"bytes,14,opt,name=name,proto3" json:"name,omitempty"`
	PhotoUrl             string   `protobuf:"bytes,15,opt,name=photo_url,json=photoUrl,proto3" json:"photo_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserRequest) Reset()         { *m = UpdateUserRequest{} }
func (m *UpdateUserRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUserRequest) ProtoMessage()    {}
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_292f630cd9eb4c90, []int{6}
}

func (m *UpdateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserRequest.Unmarshal(m, b)
}
func (m *UpdateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserRequest.Marshal(b, m, deterministic)
}
func (m *UpdateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserRequest.Merge(m, src)
}
func (m *UpdateUserRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUserRequest.Size(m)
}
func (m *UpdateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserRequest proto.InternalMessageInfo

func (m *UpdateUserRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateUserRequest) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

func (m *UpdateUserRequest) GetClientPlatformId() string {
	if m != nil {
		return m.ClientPlatformId
	}
	return ""
}

func (m *UpdateUserRequest) GetClientTypeId() string {
	if m != nil {
		return m.ClientTypeId
	}
	return ""
}

func (m *UpdateUserRequest) GetRoleId() string {
	if m != nil {
		return m.RoleId
	}
	return ""
}

func (m *UpdateUserRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *UpdateUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UpdateUserRequest) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *UpdateUserRequest) GetActive() int32 {
	if m != nil {
		return m.Active
	}
	return 0
}

func (m *UpdateUserRequest) GetExpiresAt() string {
	if m != nil {
		return m.ExpiresAt
	}
	return ""
}

func (m *UpdateUserRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateUserRequest) GetPhotoUrl() string {
	if m != nil {
		return m.PhotoUrl
	}
	return ""
}

type AddUserRelationRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RelationId           string   `protobuf:"bytes,2,opt,name=relation_id,json=relationId,proto3" json:"relation_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddUserRelationRequest) Reset()         { *m = AddUserRelationRequest{} }
func (m *AddUserRelationRequest) String() string { return proto.CompactTextString(m) }
func (*AddUserRelationRequest) ProtoMessage()    {}
func (*AddUserRelationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_292f630cd9eb4c90, []int{7}
}

func (m *AddUserRelationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddUserRelationRequest.Unmarshal(m, b)
}
func (m *AddUserRelationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddUserRelationRequest.Marshal(b, m, deterministic)
}
func (m *AddUserRelationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddUserRelationRequest.Merge(m, src)
}
func (m *AddUserRelationRequest) XXX_Size() int {
	return xxx_messageInfo_AddUserRelationRequest.Size(m)
}
func (m *AddUserRelationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddUserRelationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddUserRelationRequest proto.InternalMessageInfo

func (m *AddUserRelationRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *AddUserRelationRequest) GetRelationId() string {
	if m != nil {
		return m.RelationId
	}
	return ""
}

type UserRelationPrimaryKey struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RelationId           string   `protobuf:"bytes,2,opt,name=relation_id,json=relationId,proto3" json:"relation_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRelationPrimaryKey) Reset()         { *m = UserRelationPrimaryKey{} }
func (m *UserRelationPrimaryKey) String() string { return proto.CompactTextString(m) }
func (*UserRelationPrimaryKey) ProtoMessage()    {}
func (*UserRelationPrimaryKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_292f630cd9eb4c90, []int{8}
}

func (m *UserRelationPrimaryKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRelationPrimaryKey.Unmarshal(m, b)
}
func (m *UserRelationPrimaryKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRelationPrimaryKey.Marshal(b, m, deterministic)
}
func (m *UserRelationPrimaryKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRelationPrimaryKey.Merge(m, src)
}
func (m *UserRelationPrimaryKey) XXX_Size() int {
	return xxx_messageInfo_UserRelationPrimaryKey.Size(m)
}
func (m *UserRelationPrimaryKey) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRelationPrimaryKey.DiscardUnknown(m)
}

var xxx_messageInfo_UserRelationPrimaryKey proto.InternalMessageInfo

func (m *UserRelationPrimaryKey) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UserRelationPrimaryKey) GetRelationId() string {
	if m != nil {
		return m.RelationId
	}
	return ""
}

type UserInfoPrimaryKey struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfoPrimaryKey) Reset()         { *m = UserInfoPrimaryKey{} }
func (m *UserInfoPrimaryKey) String() string { return proto.CompactTextString(m) }
func (*UserInfoPrimaryKey) ProtoMessage()    {}
func (*UserInfoPrimaryKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_292f630cd9eb4c90, []int{9}
}

func (m *UserInfoPrimaryKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfoPrimaryKey.Unmarshal(m, b)
}
func (m *UserInfoPrimaryKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfoPrimaryKey.Marshal(b, m, deterministic)
}
func (m *UserInfoPrimaryKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfoPrimaryKey.Merge(m, src)
}
func (m *UserInfoPrimaryKey) XXX_Size() int {
	return xxx_messageInfo_UserInfoPrimaryKey.Size(m)
}
func (m *UserInfoPrimaryKey) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfoPrimaryKey.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfoPrimaryKey proto.InternalMessageInfo

func (m *UserInfoPrimaryKey) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type ResetPasswordRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	UserId               string   `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetPasswordRequest) Reset()         { *m = ResetPasswordRequest{} }
func (m *ResetPasswordRequest) String() string { return proto.CompactTextString(m) }
func (*ResetPasswordRequest) ProtoMessage()    {}
func (*ResetPasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_292f630cd9eb4c90, []int{10}
}

func (m *ResetPasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetPasswordRequest.Unmarshal(m, b)
}
func (m *ResetPasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetPasswordRequest.Marshal(b, m, deterministic)
}
func (m *ResetPasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetPasswordRequest.Merge(m, src)
}
func (m *ResetPasswordRequest) XXX_Size() int {
	return xxx_messageInfo_ResetPasswordRequest.Size(m)
}
func (m *ResetPasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetPasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ResetPasswordRequest proto.InternalMessageInfo

func (m *ResetPasswordRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *ResetPasswordRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *ResetPasswordRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type SendMessageToEmailRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	BaseUrl              string   `protobuf:"bytes,2,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	Token                string   `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendMessageToEmailRequest) Reset()         { *m = SendMessageToEmailRequest{} }
func (m *SendMessageToEmailRequest) String() string { return proto.CompactTextString(m) }
func (*SendMessageToEmailRequest) ProtoMessage()    {}
func (*SendMessageToEmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_292f630cd9eb4c90, []int{11}
}

func (m *SendMessageToEmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMessageToEmailRequest.Unmarshal(m, b)
}
func (m *SendMessageToEmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMessageToEmailRequest.Marshal(b, m, deterministic)
}
func (m *SendMessageToEmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMessageToEmailRequest.Merge(m, src)
}
func (m *SendMessageToEmailRequest) XXX_Size() int {
	return xxx_messageInfo_SendMessageToEmailRequest.Size(m)
}
func (m *SendMessageToEmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMessageToEmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendMessageToEmailRequest proto.InternalMessageInfo

func (m *SendMessageToEmailRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *SendMessageToEmailRequest) GetBaseUrl() string {
	if m != nil {
		return m.BaseUrl
	}
	return ""
}

func (m *SendMessageToEmailRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func init() {
	proto.RegisterType((*UpsertUserInfoRequest)(nil), "auth_service.UpsertUserInfoRequest")
	proto.RegisterType((*CreateUserRequest)(nil), "auth_service.CreateUserRequest")
	proto.RegisterType((*UserPrimaryKey)(nil), "auth_service.UserPrimaryKey")
	proto.RegisterType((*UserPrimaryKeyList)(nil), "auth_service.UserPrimaryKeyList")
	proto.RegisterType((*GetUserListRequest)(nil), "auth_service.GetUserListRequest")
	proto.RegisterType((*GetUserListResponse)(nil), "auth_service.GetUserListResponse")
	proto.RegisterType((*UpdateUserRequest)(nil), "auth_service.UpdateUserRequest")
	proto.RegisterType((*AddUserRelationRequest)(nil), "auth_service.AddUserRelationRequest")
	proto.RegisterType((*UserRelationPrimaryKey)(nil), "auth_service.UserRelationPrimaryKey")
	proto.RegisterType((*UserInfoPrimaryKey)(nil), "auth_service.UserInfoPrimaryKey")
	proto.RegisterType((*ResetPasswordRequest)(nil), "auth_service.ResetPasswordRequest")
	proto.RegisterType((*SendMessageToEmailRequest)(nil), "auth_service.SendMessageToEmailRequest")
}

func init() { proto.RegisterFile("user_service.proto", fileDescriptor_292f630cd9eb4c90) }

var fileDescriptor_292f630cd9eb4c90 = []byte{
	// 858 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x56, 0xdb, 0x6e, 0x23, 0x45,
	0x10, 0xf5, 0x25, 0x76, 0xe2, 0xf2, 0xe2, 0xcd, 0x16, 0xbb, 0xc9, 0xac, 0x77, 0xd1, 0x9a, 0x61,
	0x05, 0x96, 0x00, 0x47, 0x0a, 0x5f, 0x90, 0x4d, 0x56, 0x68, 0x04, 0x88, 0x68, 0x12, 0x8b, 0x8b,
	0x84, 0xa2, 0x8e, 0xa7, 0xec, 0x0c, 0x8c, 0xa7, 0x87, 0xee, 0x76, 0xc0, 0x1f, 0xc9, 0x07, 0xf0,
	0x01, 0x7c, 0x03, 0xaf, 0xa8, 0x2f, 0xb6, 0x67, 0xec, 0xb1, 0x37, 0xe2, 0x81, 0x07, 0xde, 0xa6,
	0xaa, 0x8e, 0x4f, 0x77, 0xdd, 0x8e, 0x1b, 0x70, 0x26, 0x49, 0xdc, 0x48, 0x12, 0xf7, 0xf1, 0x88,
	0x06, 0x99, 0xe0, 0x8a, 0xe3, 0x23, 0x36, 0x53, 0x77, 0x0b, 0x5f, 0x17, 0xb4, 0x65, 0x23, 0xdd,
	0x17, 0x13, 0xce, 0x27, 0x09, 0x9d, 0x18, 0xeb, 0x76, 0x36, 0x3e, 0xa1, 0x69, 0xa6, 0xe6, 0x2e,
	0xf8, 0x72, 0x3d, 0x28, 0x95, 0x98, 0x8d, 0x94, 0x8d, 0xfa, 0x3f, 0xc1, 0xb3, 0x61, 0x26, 0x49,
	0xa8, 0xa1, 0x24, 0x11, 0xa4, 0x63, 0x1e, 0xd2, 0xaf, 0x33, 0x92, 0x0a, 0x8f, 0x61, 0xdf, 0xdc,
	0x21, 0x8e, 0xbc, 0x6a, 0xaf, 0xda, 0x6f, 0x85, 0x4d, 0x6d, 0x06, 0x11, 0x7e, 0x0a, 0x7b, 0x11,
	0x53, 0xcc, 0xab, 0xf5, 0xaa, 0xfd, 0xf6, 0xe9, 0xf1, 0xc0, 0xd2, 0x0f, 0x16, 0xf4, 0x83, 0x2b,
	0x43, 0x1f, 0x1a, 0x90, 0xff, 0x57, 0x0d, 0x9e, 0x9c, 0x0b, 0x62, 0x8a, 0x34, 0xff, 0x82, 0xfb,
	0x03, 0x80, 0x4c, 0xf0, 0x9f, 0x69, 0xa4, 0x34, 0x7d, 0xcd, 0xd0, 0xb7, 0x9c, 0x27, 0x88, 0xf0,
	0x33, 0xc0, 0x51, 0x12, 0x53, 0xaa, 0x6e, 0xb2, 0x84, 0xa9, 0x31, 0x17, 0x53, 0x0d, 0xab, 0x1b,
	0xd8, 0xa1, 0x8d, 0x5c, 0xba, 0x40, 0x10, 0xe1, 0x6b, 0xe8, 0x38, 0xb4, 0x9a, 0x67, 0xa4, 0x91,
	0x7b, 0x06, 0xf9, 0xc8, 0x7a, 0xaf, 0xe7, 0x19, 0x05, 0x91, 0x4e, 0x47, 0xf0, 0xc4, 0x84, 0x1b,
	0x36, 0x1d, 0x6d, 0x06, 0x11, 0x3e, 0x85, 0x46, 0x76, 0xc7, 0x53, 0xf2, 0x9a, 0xc6, 0x6d, 0x0d,
	0xed, 0xa5, 0x29, 0x8b, 0x13, 0x6f, 0xdf, 0x7a, 0x8d, 0xa1, 0xbd, 0x09, 0x9f, 0xc4, 0xa9, 0x77,
	0x60, 0xbd, 0xc6, 0xc0, 0x2e, 0x1c, 0x64, 0x4c, 0xca, 0xdf, 0xb8, 0x88, 0xbc, 0x96, 0x09, 0x2c,
	0x6d, 0x3c, 0x82, 0x26, 0x1b, 0xa9, 0xf8, 0x9e, 0x3c, 0xe8, 0x55, 0xfb, 0x8d, 0xd0, 0x59, 0xba,
	0x02, 0xf4, 0x7b, 0x16, 0x0b, 0x92, 0x37, 0x4c, 0x79, 0x6d, 0x5b, 0x01, 0xe7, 0x39, 0x53, 0x88,
	0xb0, 0x97, 0xb2, 0x29, 0x79, 0x1d, 0x13, 0x30, 0xdf, 0xf8, 0x02, 0x5a, 0xd9, 0x1d, 0x57, 0xfc,
	0x66, 0x26, 0x12, 0xef, 0xb1, 0x3b, 0x47, 0x3b, 0x86, 0x22, 0xf1, 0x7b, 0xd0, 0xd1, 0x05, 0xbe,
	0x14, 0xf1, 0x94, 0x89, 0xf9, 0x57, 0x34, 0xc7, 0x0e, 0xd4, 0x96, 0xad, 0xab, 0xc5, 0x91, 0xff,
	0x31, 0x60, 0x11, 0xf1, 0x75, 0x2c, 0x15, 0x1e, 0x42, 0x3d, 0x8e, 0xa4, 0x57, 0xed, 0xd5, 0xfb,
	0xad, 0x50, 0x7f, 0xfa, 0x7f, 0x54, 0x01, 0xbf, 0x24, 0x33, 0x0e, 0x1a, 0xb1, 0x68, 0x99, 0x4e,
	0x3d, 0x9e, 0xc6, 0xca, 0x30, 0x36, 0x42, 0x6b, 0xe8, 0xf4, 0xf8, 0x78, 0x2c, 0x49, 0x99, 0x26,
	0x36, 0x42, 0x67, 0x69, 0xbf, 0x24, 0x26, 0x46, 0x77, 0xae, 0x6b, 0xce, 0xda, 0xd2, 0xd9, 0xbd,
	0x07, 0x77, 0xb6, 0x51, 0xd2, 0xd9, 0xe2, 0x30, 0x35, 0xd7, 0x86, 0xc9, 0x1f, 0xc2, 0xfb, 0x85,
	0x74, 0x64, 0xc6, 0x53, 0x69, 0x1a, 0x3c, 0xe2, 0xb3, 0x74, 0x99, 0x8f, 0x31, 0xb0, 0x0f, 0x0d,
	0x3d, 0xe5, 0xd2, 0xab, 0xf5, 0xea, 0xfd, 0xf6, 0x29, 0x0e, 0xf2, 0x2b, 0x37, 0x30, 0x23, 0x6c,
	0x01, 0xfe, 0x9f, 0x35, 0x78, 0x32, 0xcc, 0xa2, 0xb5, 0xc1, 0x5e, 0x2b, 0xfa, 0xff, 0x6c, 0xd0,
	0xff, 0xab, 0x61, 0x0e, 0xe1, 0xe8, 0x2c, 0x8a, 0x6c, 0x5d, 0x13, 0xa6, 0x62, 0x9e, 0xbe, 0x53,
	0x94, 0x5e, 0x41, 0x5b, 0x38, 0xec, 0xaa, 0xd2, 0xb0, 0x70, 0x05, 0x91, 0xe6, 0xcc, 0x13, 0xe6,
	0x16, 0xe5, 0xdf, 0x73, 0x7e, 0x6e, 0x57, 0x4a, 0xab, 0xe6, 0x03, 0xf8, 0x7c, 0x06, 0x4f, 0x43,
	0x92, 0xa4, 0x2e, 0x9d, 0x38, 0xe4, 0x56, 0x4b, 0xf1, 0x5f, 0x28, 0x75, 0x70, 0x6b, 0x14, 0x54,
	0xa5, 0xb6, 0xa6, 0x2a, 0xb9, 0x23, 0xea, 0x85, 0x23, 0x6e, 0xe1, 0xf9, 0x15, 0xa5, 0xd1, 0x37,
	0x24, 0x25, 0x9b, 0xd0, 0x35, 0x7f, 0xab, 0xbb, 0x99, 0x3b, 0xc7, 0xb6, 0xba, 0x9a, 0x6f, 0xf5,
	0x73, 0x38, 0xb8, 0x65, 0x92, 0x4c, 0x23, 0xec, 0x39, 0xfb, 0xda, 0x1e, 0x8a, 0x64, 0x75, 0xb1,
	0x7a, 0xee, 0x62, 0xa7, 0x7f, 0x37, 0xa1, 0xad, 0xd3, 0xbe, 0xb2, 0x5b, 0x81, 0xe7, 0x00, 0x2b,
	0x85, 0xc7, 0x57, 0xc5, 0x95, 0xd9, 0xd0, 0xfe, 0x6e, 0xc9, 0x4e, 0xf9, 0x15, 0x3c, 0x83, 0xb6,
	0xdb, 0xd2, 0x37, 0xf3, 0xe0, 0x02, 0x5f, 0x6e, 0x82, 0x56, 0x15, 0xde, 0x42, 0xf1, 0x03, 0x1c,
	0xe6, 0x16, 0x5d, 0xd3, 0x48, 0xec, 0xed, 0xe2, 0xd1, 0xb0, 0xee, 0x87, 0x45, 0x44, 0x89, 0x54,
	0xf8, 0x15, 0xbc, 0x5e, 0xde, 0xce, 0x88, 0x66, 0x6f, 0xc7, 0x6f, 0x6c, 0x92, 0x0f, 0x62, 0x3d,
	0x07, 0x58, 0x29, 0xc8, 0x7a, 0xe1, 0x36, 0xb4, 0x65, 0x4b, 0xd6, 0x17, 0x00, 0x17, 0x94, 0x90,
	0x23, 0xd9, 0x5d, 0xb7, 0xa3, 0x8d, 0xff, 0xea, 0xb7, 0xfa, 0x9d, 0xe0, 0x57, 0x30, 0x80, 0xf7,
	0x0a, 0xa3, 0x89, 0x7e, 0x91, 0xa8, 0x6c, 0x6e, 0xb7, 0x5c, 0xe8, 0x3b, 0xc0, 0xcd, 0x11, 0xc4,
	0x4f, 0x8a, 0xd8, 0xad, 0x43, 0xba, 0xe3, 0x8e, 0x43, 0x78, 0xbc, 0xa6, 0x0a, 0xf8, 0xba, 0xc8,
	0x5a, 0x2e, 0x1a, 0xdd, 0x6e, 0x89, 0x8a, 0x3b, 0x88, 0x5f, 0xc1, 0xef, 0x01, 0x43, 0x9a, 0xf2,
	0x7b, 0xda, 0xc5, 0x5c, 0x2e, 0x1d, 0xef, 0x60, 0xfe, 0x16, 0x3a, 0xc5, 0xa7, 0x15, 0x7e, 0xb4,
	0xde, 0xe3, 0x92, 0x87, 0x57, 0xf7, 0x68, 0x93, 0x54, 0x87, 0xfd, 0xca, 0x9b, 0xe3, 0x1f, 0x9f,
	0x4d, 0x28, 0x35, 0x85, 0x39, 0xc9, 0x63, 0x6e, 0x9b, 0xc6, 0xf7, 0xc5, 0x3f, 0x01, 0x00, 0x00,
	0xff, 0xff, 0x5e, 0x75, 0x84, 0x93, 0x36, 0x0a, 0x00, 0x00,
}
